# Generated by Django 5.1.6 on 2025-02-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time_start',
            new_name='time_from',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time_end',
            new_name='time_to',
        ),
        migrations.AlterField(
            model_name='event',
            name='module',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'ORG'), (20, 'TOWERS')], null=True),
        ),
    ]
