# Generated by Django 5.1.6 on 2025-02-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_rename_time_start_event_time_from_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agendaitem",
            old_name="time_start",
            new_name="time_from",
        ),
        migrations.RenameField(
            model_name="agendaitem",
            old_name="time_end",
            new_name="time_to",
        ),
    ]
