# Generated by Django 5.1.6 on 2025-02-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_googleintegration_remove_googlecalendar_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='googleevent',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
