# Generated by Django 5.1.6 on 2025-02-20 22:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_alter_event_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("event", "user")},
        ),
    ]
