# Generated by Django 5.1.6 on 2025-02-22 11:36

from django.db import migrations, models

import comunicat.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_location_coordinate_lat_location_coordinate_lon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
    ]
