# Generated by Django 5.1.6 on 2025-02-25 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_alter_location_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="path",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), default=list, size=None
                ),
                default=list,
                size=None,
            ),
        ),
    ]
