# Generated by Django 5.1.6 on 2025-02-25 16:16

import event.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_connection_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'DRAFT'), (20, 'PUBLISHED'), (30, 'CANCELLED')], default=event.enums.EventStatus['DRAFT']),
        ),
    ]
