# Generated by Django 5.1.7 on 2025-03-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_status'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendar',
            name='google_integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendars', to='integration.googleintegration'),
        ),
        migrations.DeleteModel(
            name='GoogleIntegration',
        ),
    ]
