# Generated by Django 5.1.8 on 2025-07-13 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0012_alter_googlecalendar_google_integration_and_more"),
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAlbum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("external_id", models.CharField(max_length=255, unique=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_album",
                        to="event.event",
                    ),
                ),
                (
                    "google_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_albums",
                        to="integration.googleintegration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
