# Generated by Django 5.1.11 on 2025-09-04 09:23

import event.models
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0014_eventmodule_team_alter_eventmodule_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="poster",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=event.models.get_event_poster_name,
                verbose_name="Image",
            ),
        ),
    ]
