# Generated by Django 5.1.11 on 2025-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0015_event_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
