# Generated by Django 5.1.11 on 2025-09-04 09:37
from django.db import migrations, models
from django.db.models.functions import Lower


def set_event_codes(apps, schema_editor):
    Event = apps.get_model("event", "Event")

    Event.objects.update(code=Lower("title"))


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0016_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="code",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(set_event_codes, migrations.RunPython.noop),
    ]
