# Generated by Django 5.1.11 on 2025-09-04 09:46
import zoneinfo

import django.db.models.functions.datetime
import event.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0017_event_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                models.F("code"),
                django.db.models.functions.datetime.Trunc(
                    "time_from",
                    "day",
                    output_field=models.DateTimeField(),
                    tzinfo=zoneinfo.ZoneInfo("Europe/Stockholm"),
                ),
                condition=models.Q(("status", event.enums.EventStatus["PUBLISHED"])),
                name="event_event_code_time_from_unique",
            ),
        ),
    ]
