# Generated by Django 5.1.11 on 2025-09-04 10:19

import comunicat.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0018_event_event_event_code_time_from_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="code",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
    ]
