# Generated by Django 5.1.11 on 2025-09-04 10:22

from django.db import migrations, models

import comunicat.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0019_alter_event_code_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendaitem",
            name="description",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
    ]
