# Generated by Django 5.1.11 on 2025-09-04 10:27

import comunicat.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_agendaitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='name',
            field=models.JSONField(default=comunicat.utils.models.language_field_default),
        ),
    ]
