# Generated by Django 5.1.14 on 2025-11-12 17:12

import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0021_alter_agendaitem_name"),
        ("payment", "0040_alter_payment_debit_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration",
                to="payment.paymentline",
            ),
        ),
        migrations.CreateModel(
            name="EventModulePrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("is_over_minimum_age", models.BooleanField(default=False)),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                        default="SEK",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="SEK",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="event.eventmodule",
                    ),
                ),
            ],
            options={
                "unique_together": {("module", "is_over_minimum_age")},
            },
        ),
    ]
