# Generated by Django 5.1.14 on 2025-11-18 20:16

import django.db.models.deletion
from django.db import migrations, models, transaction

import payment.api.entity


def set_registration_entities(apps, schema_editor):
    Registration = apps.get_model("event", "Registration")

    with transaction.atomic():
        for registration_obj in Registration.objects.select_related("user"):
            entity_obj = payment.api.entity.get_entity_by_key(
                email=registration_obj.user.email
            )
            registration_obj.entity_id = entity_obj.id
            registration_obj.save(update_fields=("entity_id",))


def set_registration_users(apps, schema_editor):
    Registration = apps.get_model("event", "Registration")

    with transaction.atomic():
        for registration_obj in Registration.objects.select_related("entity"):
            registration_obj.user_id = registration_obj.entity.user_id
            registration_obj.save(update_fields=("user_id",))


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0022_registration_line_eventmoduleprice"),
        ("payment", "0041_alter_payment_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="payment.entity",
            ),
        ),
        migrations.RunPython(set_registration_entities, set_registration_users),
    ]
