# Generated by Django 5.1.14 on 2025-11-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0023_registration_entity"),
        ("payment", "0041_alter_payment_transaction"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("event", "entity")},
        ),
        migrations.AlterField(
            model_name="registration",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="payment.entity",
            ),
        ),
        migrations.RemoveField(
            model_name="registration",
            name="user",
        ),
    ]
