# Generated by Django 5.1.14 on 2025-11-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
        ("event", "0024_alter_registration_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="activity.programcourse",
            ),
        ),
    ]
