# Generated by Django 5.1.14 on 2025-11-24 11:19

import event.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0025_event_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "INTERNAL"),
                    (30, "TALK"),
                    (40, "GATHERING"),
                    (50, "REHEARSAL"),
                    (60, "PERFORMANCE"),
                    (70, "COURSE"),
                ],
                default=event.enums.EventType["GENERAL"],
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendardefault",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "INTERNAL"),
                    (30, "TALK"),
                    (40, "GATHERING"),
                    (50, "REHEARSAL"),
                    (60, "PERFORMANCE"),
                    (70, "COURSE"),
                ],
                default=event.enums.EventType["GENERAL"],
                unique=True,
            ),
        ),
    ]
