# Generated by Django 5.1.14 on 2026-02-07 20:21

import event.enums
import event.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0026_alter_event_type_alter_googlecalendardefault_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=event.models.get_event_picture_name,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "INTERNAL"),
                    (30, "TALK"),
                    (40, "GATHERING"),
                    (50, "REHEARSAL"),
                    (60, "PERFORMANCE"),
                    (70, "COURSE"),
                    (80, "WORKSHOP"),
                ],
                default=event.enums.EventType["GENERAL"],
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendardefault",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "INTERNAL"),
                    (30, "TALK"),
                    (40, "GATHERING"),
                    (50, "REHEARSAL"),
                    (60, "PERFORMANCE"),
                    (70, "COURSE"),
                    (80, "WORKSHOP"),
                ],
                default=event.enums.EventType["GENERAL"],
                unique=True,
            ),
        ),
    ]
