# Generated by Django 5.1.14 on 2026-02-08 08:44

import comunicat.utils.models
from django.db import migrations, models


def set_event_title_lang(apps, schema_editor):
    Event = apps.get_model("event.Event")

    event_updates = []
    for event_obj in Event.objects.all():
        event_obj.title_lang = {
            locale: event_obj.title
            for locale, __ in comunicat.utils.models.language_field_default()
        }
        event_updates.append(event_obj)

    Event.objects.bulk_update(event_updates, fields=("title_lang",))


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0027_event_picture_alter_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="title_lang",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
        migrations.RunPython(set_event_title_lang, migrations.RunPython.noop),
    ]
