# Generated by Django 5.1.14 on 2026-02-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0028_event_title_lang"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
    ]
