# Generated by Django 5.1.14 on 2026-02-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0029_remove_event_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="title_lang",
            new_name="title",
        ),
    ]
