# Generated by Django 5.1.14 on 2026-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0030_rename_title_lang_event_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlealbum",
            name="external_shared_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
