# Generated by Django 5.1.14 on 2026-02-16 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_google_photo_albums(apps, schema_editor):
    GoogleAlbum = apps.get_model("event.GoogleAlbum")
    GooglePhotosAlbum = apps.get_model("event.GooglePhotosAlbum")

    google_photos_album_creates = []
    for google_album_obj in GoogleAlbum.objects.filter(
        external_shared_id__isnull=False
    ):
        google_photos_album_creates.append(
            GooglePhotosAlbum(
                album=google_album_obj, external_id=google_album_obj.external_shared_id
            )
        )

    GooglePhotosAlbum.objects.bulk_create(google_photos_album_creates)


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0031_googlealbum_external_shared_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleDriveAlbum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("external_id", models.CharField(max_length=255, unique=True)),
                (
                    "album",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive_album",
                        to="event.googlealbum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GooglePhotosAlbum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("external_id", models.CharField(max_length=255, unique=True)),
                (
                    "album",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos_album",
                        to="event.googlealbum",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_google_photo_albums, migrations.RunPython.noop),
    ]
