# Generated by Django 5.1.14 on 2026-02-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0032_googledrivealbum_googlephotoalbum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googlealbum",
            name="external_shared_id",
        ),
        migrations.AlterField(
            model_name="googlephotosalbum",
            name="album",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_photo_album",
                to="event.googlealbum",
            ),
        ),
    ]
