# Generated by Django 5.1.15 on 2026-04-15 18:53

import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.db import migrations, models
from django.conf import settings
from django.db.models import F, UUIDField
from django.db.models.functions import Cast


def create_event_prices(apps, schema_editor):
    EventModulePrice = apps.get_model("event.EventModulePrice")
    EventPrice = apps.get_model("event.EventPrice")

    event_price_creates = []
    for event_module_price_obj in EventModulePrice.objects.all():
        event_price_creates.append(
            EventPrice(
                event=event_module_price_obj.module.event,
                module=event_module_price_obj.module.module,
                amount=event_module_price_obj.amount,
                age_from=(
                    settings.MODULE_ALL_USER_MINIMUM_AGE
                    if event_module_price_obj.is_over_minimum_age
                    else None
                ),
                age_to=(
                    None
                    if event_module_price_obj.is_over_minimum_age
                    else settings.MODULE_ALL_USER_MINIMUM_AGE - 1
                ),
            )
        )

    if event_price_creates:
        EventPrice.objects.bulk_create(event_price_creates)


def update_registrations(apps, schema_editor):
    Registration = apps.get_model("event.Registration")
    EventPrice = apps.get_model("event.EventPrice")
    PaymentLine = apps.get_model("payment.PaymentLine")

    registration_updates = []
    for registration_obj in Registration.objects.all():
        amount = sum(
            PaymentLine.objects.filter(
                item_type__app_label="event",
                item_type__model="registration",
            )
            .annotate(item_uuid=Cast(F("item_id"), output_field=UUIDField()))
            .filter(
                item_uuid=registration_obj.id,
            )
            .values_list("amount", flat=True)
        )

        if not amount:
            continue

        # Not the right filter but it does the trick at the time of applying this for the intended system
        event_price_obj = EventPrice.objects.filter(
            event=registration_obj.event, amount=amount
        ).first()

        if not event_price_obj:
            continue

        registration_obj.price = event_price_obj
        registration_updates.append(registration_obj)

    if registration_updates:
        Registration.objects.bulk_update(registration_updates, fields=("price",))


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0033_remove_googlealbum_external_shared_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlephotosalbum",
            name="album",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos_album",
                to="event.googlealbum",
            ),
        ),
        migrations.CreateModel(
            name="EventPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "module",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(10, "ORG"), (20, "TOWERS")], null=True
                    ),
                ),
                ("age_from", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("age_to", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("min_registrations", models.PositiveSmallIntegerField(default=0)),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                        default="SEK",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="SEK",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="event.eventprice",
            ),
        ),
        migrations.RunPython(create_event_prices, migrations.RunPython.noop),
        migrations.RunPython(update_registrations, migrations.RunPython.noop),
    ]
