# Generated by Django 5.1.15 on 2026-04-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0034_registration_amount_registration_amount_currency_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventModulePrice",
        ),
    ]
