# Generated by Django 5.1.15 on 2026-04-17 10:16

import uuid

import django.db.models.deletion
from django.db import migrations, models

import comunicat.utils.models
import event.enums


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0035_delete_eventmoduleprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "title",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "SHORT"),
                            (20, "LONG"),
                            (30, "BOOLEAN"),
                            (40, "CHOICE"),
                        ],
                        default=event.enums.EventQuestionType["SHORT"],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "order")},
            },
        ),
    ]
