# Generated by Django 5.1.15 on 2026-04-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0036_eventquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
