# Generated by Django 5.1.15 on 2026-04-17 11:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0037_registration_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSignup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "module",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(10, "ORG"), (20, "TOWERS")], null=True
                    ),
                ),
                ("time_from", models.DateTimeField(blank=True, null=True)),
                ("time_to", models.DateTimeField(blank=True, null=True)),
                (
                    "max_registrations",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signups",
                        to="event.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
