# Generated by Django 5.1.15 on 2026-04-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0038_eventsignup"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventprice",
            unique_together={("event", "module", "age_from", "age_to")},
        ),
        migrations.AlterUniqueTogether(
            name="eventsignup",
            unique_together={("event", "module")},
        ),
    ]
