# Generated by Django 5.1.15 on 2026-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0039_alter_eventprice_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventquestion",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
