# Generated by Django 5.2.16 on 2026-07-26 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0040_eventquestion_is_required"),
        ("payment", "0050_source_provider_alter_payment_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="event.event",
                    ),
                ),
                (
                    "registration_credit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_accounts_registration_credit",
                        to="payment.account",
                    ),
                ),
                (
                    "registration_debit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_accounts_registration_debit",
                        to="payment.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "event accounts",
                "verbose_name_plural": "event accounts",
            },
        ),
    ]
