# Generated by Django 5.2.17 on 2026-08-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0041_eventaccounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodule",
            name="require_user",
            field=models.BooleanField(default=True),
        ),
    ]
