# Generated by Django 5.2.17 on 2026-08-30 11:28

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def update_registration_owners(apps, schema_editor):
    Registration = apps.get_model("event.Registration")

    Registration.objects.update(owner_id=F("entity_id"))


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0042_eventmodule_require_user"),
        ("payment", "0063_entity_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_registrations",
                to="payment.entity",
            ),
        ),
        migrations.RunPython(update_registration_owners, migrations.RunPython.noop),
    ]
