# Generated by Django 5.2.17 on 2026-08-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0043_registration_owner"),
        ("payment", "0063_entity_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_registrations",
                to="payment.entity",
            ),
        ),
    ]
