# Generated by Django 5.2.17 on 2026-09-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0044_alter_registration_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendar",
            name="language",
            field=models.CharField(default="en", max_length=255),
            preserve_default=False,
        ),
    ]
