# Generated by Django 5.2.17 on 2026-09-20 21:27

import comunicat.utils.models
import event.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0045_googlecalendar_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventseries",
            name="name",
        ),
        migrations.AddField(
            model_name="eventseries",
            name="code",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventseries",
            name="description",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="module",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(10, "ORG"), (20, "TOWERS")], null=True
            ),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="title",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
        migrations.AddField(
            model_name="eventseries",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "INTERNAL"),
                    (30, "TALK"),
                    (40, "GATHERING"),
                    (50, "REHEARSAL"),
                    (60, "PERFORMANCE"),
                    (70, "COURSE"),
                    (80, "WORKSHOP"),
                ],
                default=event.enums.EventType["GENERAL"],
            ),
        ),
    ]
