# Generated by Django 5.2.17 on 2026-10-01 16:49

import comunicat.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0046_remove_eventseries_name_eventseries_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventseries",
            options={
                "verbose_name": "event series",
                "verbose_name_plural": "event series",
            },
        ),
        migrations.AddField(
            model_name="registration",
            name="token",
            field=models.CharField(
                default=comunicat.utils.crypto.gen_random_token, max_length=255
            ),
        ),
    ]
