# Generated by Django 5.2.17 on 2026-10-03 08:32

import comunicat.utils.crypto
import event.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0047_alter_eventseries_options_registration_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=event.models.get_event_picture_name,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="poster",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=event.models.get_event_poster_name,
                verbose_name="poster",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="token",
            field=models.CharField(
                default=comunicat.utils.crypto.gen_random_token,
                max_length=255,
                unique=True,
            ),
        ),
    ]
