# Generated by Django 5.2.17 on 2026-10-05 15:17

import event.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0048_alter_event_picture_alter_event_poster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="has_attended",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "REQUESTED"),
                    (20, "ACTIVE"),
                    (30, "CANCELLED"),
                    (40, "TENTATIVE"),
                    (50, "ATTENDED"),
                ],
                default=event.enums.RegistrationStatus["REQUESTED"],
            ),
        ),
        migrations.AlterField(
            model_name="registrationlog",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "REQUESTED"),
                    (20, "ACTIVE"),
                    (30, "CANCELLED"),
                    (40, "TENTATIVE"),
                    (50, "ATTENDED"),
                ]
            ),
        ),
    ]
