# Generated by Django 5.1.6 on 2025-02-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('user', '0004_user_origin_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipuser',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_users', to='user.family'),
        ),
    ]
