# Generated by Django 5.1.6 on 2025-02-14 14:25

import membership.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_alter_membershipuser_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipmodule",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "REQUESTED"),
                    (1, "PROCESSING"),
                    (2, "ACTIVE"),
                    (3, "EXPIRED"),
                ],
                default=membership.enums.MembershipStatus["REQUESTED"],
            ),
        ),
        migrations.AlterField(
            model_name="membershipmodule",
            name="module",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "ORG"), (20, "TOWERS")]
            ),
        ),
    ]
