# Generated by Django 5.1.6 on 2025-02-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_membershipmodule_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membership",
            old_name="users",
            new_name="user",
        ),
    ]
