# Generated by Django 5.1.6 on 2025-02-14 15:10

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0007_alter_membershipmodule_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipmodule",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
    ]
