# Generated by Django 5.1.6 on 2025-02-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0008_alter_membershipmodule_amount_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membership",
            old_name="user",
            new_name="users",
        ),
    ]
