# Generated by Django 5.1.8 on 2025-06-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_membership_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new', to='membership.membership'),
        ),
    ]
