# Generated by Django 5.2.16 on 2026-07-24 11:17

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0011_membership_previous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipmodule",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
    ]
