version: "3.9"

services:
  backend:
    image: ghcr.io/castellersestocolm/backend:${BUILD_TAG:-dev}
    build:
      context: backend
      args:
        - BUILD_TARGET=${BUILD_TARGET:-dev}
    deploy:
      replicas: 2
    stdin_open: true
    tty: true
    restart: on-failure
    entrypoint: ["wait-for-it", "database:5432", "--", "python", "manage.py"]
    command: ["runserver", "0.0.0.0:8000"]
    networks:
      - comunicat
    volumes:
      - media-files:/backend/backend/media
      - internal-media:/backend/internal_media:cached
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - database
      - redis
      - mail
    env_file:
      - ./envs/local.env
#  frontend-org:
#    image: ghcr.io/castellersestocolm/frontend-org:${BUILD_TAG:-dev}
#    build: frontend-org
#    stdin_open: true
#    tty: true
#    restart: on-failure
#    entrypoint: ["npm"]
#    command: ["start"]
#    networks:
#      - comunicat
#    volumes:
#      - ./frontend-org/app:/frontend-org/app:cached
#    ports:
#      - target: 3000
#        published: 3100
#        protocol: tcp
#        mode: host
#    env_file:
#      - ./envs/local.env
  frontend-towers:
    image: ghcr.io/castellersestocolm/frontend-towers:${BUILD_TAG:-dev}
    build:
      context: frontend-towers
      dockerfile: Dockerfile-prod
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://localhost:8000/api/1.0}
        - REACT_APP_ORG_BASE_URL=${REACT_APP_ORG_BASE_URL:-http://localhost:3200}
        - REACT_APP_ORG_INFO_EMAIL=${REACT_APP_ORG_INFO_EMAIL:-info@lesquatrebarres.org}
        - REACT_APP_TOWERS_BASE_URL=${REACT_APP_TOWERS_BASE_URL:-http://localhost:3100}
        - REACT_APP_TOWERS_INFO_EMAIL=${REACT_APP_TOWERS_INFO_EMAIL:-info@castellersestocolm.se}
    deploy:
      replicas: 1
    stdin_open: true
    tty: true
    restart: on-failure
    networks:
      - comunicat
    ports:
      - target: 80
        published: 3200
        protocol: tcp
        mode: host
  database:
    image: postgres:17.2
    deploy:
      replicas: 1
    ports:
      - 5432:5432
    networks:
      - comunicat
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      DJANGO_WATCHMAN_TIMEOUT: 20
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: comunicat
      POSTGRES_PASSWORD: comunicat
      POSTGRES_DB: comunicat
  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data
    ports:
      - 6390:6379
    networks:
      - comunicat
  worker:
    image: ghcr.io/castellersestocolm/backend:${BUILD_TAG:-dev}
    stdin_open: true
    tty: true
    entrypoint: [ "celery" ]
    command: [ "-A", "comunicat", "worker", "-Q", "default" ]
    depends_on:
      - redis
      - database
      - mail
    volumes:
      - media-files:/backend/backendmedia
      - internal-media:/backend/internal_media:cached
    networks:
      - comunicat
    env_file:
      - ./envs/local.env
  beat:
    image: ghcr.io/castellersestocolm/backend:${BUILD_TAG:-dev}
    deploy:
      replicas: 1
    entrypoint: [ "celery" ]
    command:
      [ "-A", "comunicat", "beat", "--pidfile=", "-s", "/data/celerybeat-schedule", "-l", "debug" ]
    depends_on:
      - worker
    volumes:
      - celerybeat-data:/data
    networks:
      - comunicat
    env_file:
      - ./envs/local.env
  pinyator:
    image: ghcr.io/castellersestocolm/pinyator:${BUILD_TAG:-dev}
    build: pinyator
    deploy:
      replicas: 1
    stdin_open: true
    tty: true
    restart: on-failure
    networks:
      - comunicat
    volumes:
      - ./pinyator/src:/pinyator/pinyator:cached
    ports:
      - target: 80
        published: 8100
        protocol: tcp
        mode: host
    depends_on:
      - php
    env_file:
      - ./envs/local.env
  php:
    image: ghcr.io/castellersestocolm/php:${BUILD_TAG:-dev}
    build: php
    deploy:
      replicas: 1
    stdin_open: true
    tty: true
    restart: on-failure
    # entrypoint: ["wait-for-it", "database:5432", "--", "php"]
    # command: ["-S", "0.0.0.0:8110", "./pinyator/Pinyator.php"]
    networks:
      - comunicat
    volumes:
      - ./pinyator/src:/pinyator/pinyator:cached
    depends_on:
      - mysql
    env_file:
      - ./envs/local.env
  mysql:
    image: mysql:8.4.4
    deploy:
      replicas: 1
    ports:
      - 3306:3306
    networks:
      - comunicat
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pinyator
      MYSQL_USER: pinyator
      MYSQL_PASSWORD: pinyator
      MYSQL_DATABASE: pinyator
  mail:
    image: ghcr.io/docker-mailserver/docker-mailserver:15.0.0
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 587
        published: 587
        protocol: tcp
        mode: host
      - target: 993
        published: 993
        protocol: tcp
        mode: host
      - target: 995
        published: 995
        protocol: tcp
        mode: host
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
    environment:
      - PERMIT_DOCKER=network
      - DEFAULT_RELAY_HOST=[smtp-relay.gmail.com]:587
      - SSL_TYPE=
      - OVERRIDE_HOSTNAME=mail.castellersestocolm.se
      - LOG_LEVEL=debug
    networks:
      - comunicat
  proxy:
    image: haproxytech/haproxy-alpine:3.2
    deploy:
      replicas: 1
    restart: on-failure
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./docker-data/haproxy/:/usr/local/etc/haproxy:ro
    depends_on:
      - backend
    networks:
      - comunicat

volumes:
  media-files:
  internal-media:
  postgres-data:
  mysql-data:
  redis-data:
  celerybeat-data:

networks:
  comunicat:
    ipam:
      config:
        - subnet: 172.24.0.0/16
