# Generated by Django 5.1.6 on 2025-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_paymentline_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
