# Generated by Django 5.1.6 on 2025-02-16 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_source_alter_paymentline_vat_account_payment_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='payment.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
