# Generated by Django 5.1.6 on 2025-02-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_payment_account_paymentline_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transactions',
            new_name='transaction',
        ),
    ]
