# Generated by Django 5.1.6 on 2025-02-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0018_transactionimport_file_alter_transactionimport_input"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
