# Generated by Django 5.1.7 on 2025-04-07 11:56

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import payment.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_transactionimport_date_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('type', models.PositiveSmallIntegerField(choices=[(10, 'PERSONAL'), (20, 'BUSINESS')], default=payment.enums.ReceiptType['PERSONAL'])),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'CREATED'), (20, 'DELETED')], default=payment.enums.ReceiptStatus['CREATED'])),
                ('file', models.FileField(upload_to='payment/receipt/file/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('SEK', 'Swedish Krona')], default='SEK', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='SEK', max_digits=7)),
                ('vat', models.PositiveSmallIntegerField(default=0)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='payment.payment')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='payment.receipt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
