# Generated by Django 5.1.7 on 2025-04-18 13:49

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import payment.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_transactionimport_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.PositiveIntegerField(blank=True, choices=[(10, 'CASH'), (20, 'TRANSFER'), (30, 'CARD'), (75201, 'SE_SWISH'), (75202, 'SE_PLUSGIRO')], null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.PositiveIntegerField(choices=[(10, 'CASH'), (20, 'TRANSFER'), (30, 'CARD'), (75201, 'SE_SWISH'), (75202, 'SE_PLUSGIRO')], default=payment.enums.PaymentMethod['TRANSFER']),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'CREATED'), (20, 'PROCESSING'), (30, 'APPROVED'), (40, 'REJECTED'), (50, 'DELETED')], default=payment.enums.ExpenseStatus['CREATED'])),
                ('file', models.FileField(blank=True, null=True, upload_to='payment/expense/file/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='payment.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'CREATED'), (20, 'PROCESSING'), (30, 'APPROVED'), (40, 'REJECTED'), (50, 'DELETED')])),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payment.expense')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.PositiveSmallIntegerField(choices=[(10, 'PERSONAL'), (20, 'BUSINESS')], default=payment.enums.ReceiptType['PERSONAL'])),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'CREATED'), (20, 'DELETED')], default=payment.enums.ReceiptStatus['CREATED'])),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('SEK', 'Swedish Krona')], default='SEK', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='SEK', max_digits=7)),
                ('vat', models.PositiveSmallIntegerField(default=0)),
                ('file', models.FileField(upload_to='payment/receipt/file/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_receipts', to='payment.expense')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paymentline',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_lines', to='payment.receipt'),
        ),
    ]
