# Generated by Django 5.1.7 on 2025-04-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0023_alter_payment_method_alter_transaction_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="payment.expense",
            ),
        ),
    ]
