# Generated by Django 5.1.7 on 2025-04-07 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_receipt_date_receipt_description_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'CREATED'), (20, 'PROCESSING'), (30, 'APPROVED'), (40, 'REJECTED'), (50, 'DELETED')])),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payment.expense')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
