# Generated by Django 5.1.7 on 2025-04-18 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0025_alter_expense_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="file",
            field=models.FileField(
                storage="private",
                upload_to="payment/receipt/file/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transactionimport",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage="private",
                upload_to="payment/transactionimport/file/",
                validators=[django.core.validators.FileExtensionValidator(["csv"])],
            ),
        ),
    ]
