# Generated by Django 5.1.8 on 2025-05-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0029_alter_expense_file_alter_receipt_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="payment.source",
            ),
        ),
    ]
