# Generated by Django 5.1.8 on 2025-05-16 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0031_receipt_entity_part_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="payment.entity",
            ),
        ),
    ]
