# Generated by Django 5.1.8 on 2025-05-16 10:29

import django.db.models.deletion
from django.db import migrations, models


def set_receipt_entity(apps, schema_editor):
    Entity = apps.get_model("payment.Entity")
    Receipt = apps.get_model("payment.Receipt")

    receipt_updates = []

    entity_obj = Entity.objects.first() or Entity.object.create()

    for receipt_obj in Receipt.objects.select_related("expense"):
        if receipt_obj.expense:
            receipt_obj.entity = receipt_obj.expense.entity
        else:
            receipt_obj.entity = entity_obj
        receipt_updates.append(receipt_obj)

    Receipt.objects.bulk_update(receipt_updates, fields=("entity",))


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0030_alter_transaction_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="entity",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                blank=True,
                null=True,
                related_name="receipts",
                to="payment.entity",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_receipt_entity),
    ]
