# Generated by Django 5.1.8 on 2025-07-22 12:19

import comunicat.utils.models
import djmoney.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0031_receipt_entity_part_2"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "name",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                (
                    "method",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "CASH"),
                            (20, "TRANSFER"),
                            (30, "CARD"),
                            (75201, "SE_SWISH"),
                            (75202, "SE_PLUSGIRO"),
                        ]
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="paymentline",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="amount_end_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="amount_start_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
    ]
