# Generated by Django 5.1.8 on 2025-07-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0032_paymentprovider_alter_paymentline_amount_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentprovider",
            name="method",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "CASH"),
                    (20, "TRANSFER"),
                    (30, "CARD"),
                    (75201, "SE_SWISH"),
                    (75202, "SE_PLUSGIRO"),
                ]
            ),
        ),
    ]
