# Generated by Django 5.1.11 on 2025-07-22 13:42

import django.db.models.deletion
import payment.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0033_alter_paymentprovider_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "PENDING"),
                            (20, "PROCESSING"),
                            (30, "COMPLETED"),
                            (40, "CANCELED"),
                        ],
                        default=payment.enums.PaymentStatus["PENDING"],
                    ),
                ),
                ("external_id", models.CharField(max_length=255, unique=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="payment.paymentprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
