# Generated by Django 5.1.11 on 2025-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0034_paymentorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprovider",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
