# Generated by Django 5.1.11 on 2025-07-22 14:00

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0035_paymentprovider_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprovider",
            name="picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="payment/payment-provider/picture/",
                verbose_name="Image",
            ),
        ),
    ]
