# Generated by Django 5.1.11 on 2025-07-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0036_paymentprovider_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentorder",
            name="external_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
