# Generated by Django 5.1.11 on 2025-10-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0039_paymentorderproviderlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="debit_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_payments",
                to="payment.payment",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.transaction",
            ),
        ),
    ]
