# Generated by Django 5.1.14 on 2025-11-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0040_alter_payment_debit_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payment.transaction",
            ),
        ),
    ]
