# Generated by Django 5.1.14 on 2025-12-04 09:45

from django.db import migrations, models


def set_entity_preferred_language(apps, schema_editor):
    Entity = apps.get_model("payment.Entity")

    entity_updates = []
    for entity_obj in Entity.objects.select_related("user"):
        if entity_obj.user and entity_obj.user.preferred_language:
            entity_obj.preferred_language = entity_obj.user.preferred_language
            entity_updates.append(entity_obj)

    Entity.objects.bulk_update(entity_updates, fields=("preferred_language",))


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0041_alter_payment_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(set_entity_preferred_language, migrations.RunPython.noop),
    ]
