# Generated by Django 5.1.14 on 2026-01-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payment", "0042_entity_preferred_language"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-created_at"], name="payment_pay_created_c2327c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentline",
            index=models.Index(
                fields=["-created_at"], name="payment_pay_created_980a13_idx"
            ),
        ),
    ]
