# Generated by Django 5.1.14 on 2026-01-27 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0043_payment_payment_pay_created_c2327c_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["firstname", "lastname", "email", "-created_at"],
                name="payment_ent_firstna_6c94e9_idx",
            ),
        ),
    ]
