# Generated by Django 5.1.14 on 2026-03-31 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_entity_aliases(apps, schema_editor):
    Entity = apps.get_model("payment.Entity")
    EntityAlias = apps.get_model("payment.EntityAlias")

    entity_alias_creates = []
    for entity_obj in Entity.objects.prefetch_related(
        "payments", "payments__transaction"
    ):
        entity_aliases = set()
        for payment_obj in entity_obj.payments.all():
            if payment_obj.transaction and payment_obj.transaction.sender:
                entity_aliases.add(payment_obj.transaction.sender)
        for entity_alias in entity_aliases:
            entity_alias_creates.append(
                EntityAlias(entity_id=entity_obj.id, alias=entity_alias)
            )

    if entity_alias_creates:
        EntityAlias.objects.bulk_create(entity_alias_creates)


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0044_entity_payment_ent_firstna_6c94e9_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="category",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (10, "ASSETS"),
                    (20, "SAVINGS"),
                    (30, "GRANTS"),
                    (40, "DONATIONS"),
                    (50, "DEBTS"),
                    (60, "MEMBERSHIPS"),
                    (70, "EVENTS"),
                    (80, "EXPENSES"),
                    (90, "RENT"),
                    (100, "SALARIES"),
                    (110, "TAX"),
                    (120, "INSURANCE"),
                    (130, "LOSSES"),
                    (140, "SALES"),
                    (150, "INTEREST"),
                    (160, "ERRORS"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("alias", models.CharField(max_length=255)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="payment.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity alias",
                "verbose_name_plural": "entity aliases",
                "indexes": [
                    models.Index(fields=["alias"], name="payment_ent_alias_4b5c4c_idx")
                ],
                "unique_together": {("entity", "alias")},
            },
        ),
        migrations.RunPython(create_entity_aliases, migrations.RunPython.noop),
    ]
