# Generated by Django 5.1.15 on 2026-04-01 13:06

import uuid

import django.db.models.deletion
from django.db import migrations, models

import payment.enums


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0045_alter_account_category_entityalias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (10, "CASH"),
                    (20, "TRANSFER"),
                    (30, "CARD"),
                    (110, "PAYPAL"),
                    (75201, "SE_SWISH"),
                    (75202, "SE_PLUSGIRO"),
                    (75203, "SE_BANKGIRO"),
                    (75204, "SE_TRANSFER"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentprovider",
            name="method",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "CASH"),
                    (20, "TRANSFER"),
                    (30, "CARD"),
                    (110, "PAYPAL"),
                    (75201, "SE_SWISH"),
                    (75202, "SE_PLUSGIRO"),
                    (75203, "SE_BANKGIRO"),
                    (75204, "SE_TRANSFER"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="method",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "CASH"),
                    (20, "TRANSFER"),
                    (30, "CARD"),
                    (110, "PAYPAL"),
                    (75201, "SE_SWISH"),
                    (75202, "SE_PLUSGIRO"),
                    (75203, "SE_BANKGIRO"),
                    (75204, "SE_TRANSFER"),
                ],
                default=payment.enums.PaymentMethod["TRANSFER"],
            ),
        ),
        migrations.CreateModel(
            name="EntityPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "method",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "CASH"),
                            (20, "TRANSFER"),
                            (30, "CARD"),
                            (110, "PAYPAL"),
                            (75201, "SE_SWISH"),
                            (75202, "SE_PLUSGIRO"),
                            (75203, "SE_BANKGIRO"),
                            (75204, "SE_TRANSFER"),
                        ],
                        default=payment.enums.PaymentMethod["TRANSFER"],
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="payment.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity payment method",
                "verbose_name_plural": "entity payment methods",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("entity", "is_primary"),
                        name="payment_entitypaymentmethod_is_primary_uniq",
                    )
                ],
            },
        ),
    ]
