# Generated by Django 5.1.15 on 2026-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0046_alter_payment_method_alter_paymentprovider_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitypaymentmethod",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
