# Generated by Django 5.2.16 on 2026-07-24 11:17

import payment.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0048_accountevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitypaymentmethod",
            name="method",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "CASH"),
                    (20, "TRANSFER"),
                    (30, "CARD"),
                    (110, "PAYPAL"),
                    (120, "SUMUP"),
                    (75201, "SE_SWISH"),
                    (75202, "SE_PLUSGIRO"),
                    (75203, "SE_BANKGIRO"),
                    (75204, "SE_TRANSFER"),
                ],
                default=payment.enums.PaymentMethod["TRANSFER"],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (10, "CASH"),
                    (20, "TRANSFER"),
                    (30, "CARD"),
                    (110, "PAYPAL"),
                    (120, "SUMUP"),
                    (75201, "SE_SWISH"),
                    (75202, "SE_PLUSGIRO"),
                    (75203, "SE_BANKGIRO"),
                    (75204, "SE_TRANSFER"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "CREATED"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELED"),
                ],
                default=payment.enums.PaymentStatus["CREATED"],
            ),
        ),
        migrations.AlterField(
            model_name="paymentlog",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "CREATED"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELED"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "CREATED"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELED"),
                ],
                default=payment.enums.PaymentStatus["CREATED"],
            ),
        ),
        migrations.AlterField(
            model_name="paymentprovider",
            name="method",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "CASH"),
                    (20, "TRANSFER"),
                    (30, "CARD"),
                    (110, "PAYPAL"),
                    (120, "SUMUP"),
                    (75201, "SE_SWISH"),
                    (75202, "SE_PLUSGIRO"),
                    (75203, "SE_BANKGIRO"),
                    (75204, "SE_TRANSFER"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="method",
            field=models.PositiveIntegerField(
                choices=[
                    (10, "CASH"),
                    (20, "TRANSFER"),
                    (30, "CARD"),
                    (110, "PAYPAL"),
                    (120, "SUMUP"),
                    (75201, "SE_SWISH"),
                    (75202, "SE_PLUSGIRO"),
                    (75203, "SE_BANKGIRO"),
                    (75204, "SE_TRANSFER"),
                ],
                default=payment.enums.PaymentMethod["TRANSFER"],
            ),
        ),
    ]
