# Generated by Django 5.2.16 on 2026-07-25 18:52

import django.db.models.deletion
import payment.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0049_alter_entitypaymentmethod_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="provider",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source",
                to="payment.paymentprovider",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "CREATED"),
                    (10, "PENDING"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELED"),
                ],
                default=payment.enums.PaymentStatus["CREATED"],
            ),
        ),
        migrations.AlterField(
            model_name="paymentlog",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "CREATED"),
                    (10, "PENDING"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELED"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "CREATED"),
                    (10, "PENDING"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELED"),
                ],
                default=payment.enums.PaymentStatus["CREATED"],
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "BANK"), (20, "PROVIDER")],
                default=payment.enums.SourceType["BANK"],
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("type", payment.enums.SourceType["PROVIDER"]),
                        ("provider__isnull", False),
                    ),
                    models.Q(
                        models.Q(
                            ("type", payment.enums.SourceType["PROVIDER"]),
                            _negated=True,
                        ),
                        ("provider__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="payment_source_type_provider",
            ),
        ),
    ]
