# Generated by Django 5.2.16 on 2026-07-26 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0041_eventaccounts"),
        ("payment", "0050_source_provider_alter_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountevent",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_accounts",
                to="event.event",
            ),
        ),
    ]
