# Generated by Django 5.2.16 on 2026-08-02 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0051_alter_accountevent_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprovider",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_providers",
                to="payment.entity",
            ),
        ),
        migrations.CreateModel(
            name="PaymentProviderAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "payment_fees",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_provider_accounts_payment_fees",
                        to="payment.account",
                    ),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="payment.paymentprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment provider accounts",
                "verbose_name_plural": "payment provider accounts",
            },
        ),
    ]
