# Generated by Django 5.2.16 on 2026-08-02 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0052_paymentprovider_entity_paymentprovideraccounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="source_bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_providers",
                to="payment.source",
            ),
        ),
    ]
