# Generated by Django 5.2.16 on 2026-08-02 12:22

import payment.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0053_source_source_bank"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("type", payment.enums.SourceType["PROVIDER"]),
                        ("source_bank__isnull", False),
                    ),
                    models.Q(
                        models.Q(
                            ("type", payment.enums.SourceType["PROVIDER"]),
                            _negated=True,
                        ),
                        ("source_bank__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="payment_source_bank_type_provider",
            ),
        ),
    ]
