# Generated by Django 5.2.17 on 2026-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0054_source_payment_source_bank_type_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="extra",
            field=models.JSONField(default=dict),
        ),
    ]
