# Generated by Django 5.2.17 on 2026-08-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0055_paymentorder_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprovider",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
