# Generated by Django 5.2.17 on 2026-08-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0056_paymentprovider_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="debit_payment_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_payment_orders",
                to="payment.paymentorder",
            ),
        ),
    ]
