# Generated by Django 5.2.17 on 2026-08-22 07:58

import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0057_paymentorder_debit_payment_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionImportLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("row", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "method",
                    models.PositiveIntegerField(
                        choices=[
                            (10, "CASH"),
                            (20, "TRANSFER"),
                            (30, "CARD"),
                            (110, "PAYPAL"),
                            (120, "SUMUP"),
                            (75201, "SE_SWISH"),
                            (75202, "SE_PLUSGIRO"),
                            (75203, "SE_BANKGIRO"),
                            (75204, "SE_TRANSFER"),
                        ]
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                        default="SEK",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="SEK", max_digits=7
                    ),
                ),
                ("vat", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                ("sender", models.CharField(blank=True, max_length=255, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_accounting", models.DateField()),
                ("date_interest", models.DateField(blank=True, null=True)),
                (
                    "transaction_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_lines",
                        to="payment.transactionimport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
