# Generated by Django 5.2.17 on 2026-08-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0058_transactionimportline"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionimportline",
            name="extra",
            field=models.JSONField(default=dict),
        ),
    ]
