# Generated by Django 5.2.17 on 2026-08-22 08:16

import payment.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0059_transactionimportline_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionimportline",
            name="transactions",
            field=models.ManyToManyField(
                blank=True, related_name="import_lines", to="payment.transaction"
            ),
        ),
        migrations.AlterField(
            model_name="transactionimport",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "CREATED"),
                    (15, "PROCESSED"),
                    (20, "RUNNING"),
                    (30, "COMPLETED"),
                    (40, "ERRORED"),
                ],
                default=payment.enums.TransactionImportStatus["CREATED"],
            ),
        ),
    ]
