# Generated by Django 5.2.17 on 2026-08-22 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0060_transactionimportline_transactions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_import_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_transactions",
                to="payment.transactionimportline",
            ),
        ),
    ]
