# Generated by Django 5.2.17 on 2026-08-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0061_transaction_transaction_import_line"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_import_line",
            new_name="import_line",
        ),
    ]
