# Generated by Django 5.2.17 on 2026-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0062_rename_transaction_import_line_transaction_import_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
