# Generated by Django 5.2.17 on 2026-09-30 11:16

import payment.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0064_paymentrequest_paymentrequestline_paymentrequestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequestline",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "CREATED"),
                    (10, "PENDING"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELED"),
                ],
                default=payment.enums.PaymentStatus["CREATED"],
            ),
        ),
    ]
