# Generated by Django 5.2.17 on 2026-10-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0049_registration_has_attended_alter_registration_status_and_more"),
        ("payment", "0065_paymentrequestline_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentline",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_lines",
                to="event.event",
            ),
        ),
        migrations.AlterField(
            model_name="paymentline",
            name="debit_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_lines",
                to="payment.paymentline",
            ),
        ),
        migrations.AlterField(
            model_name="paymentline",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_lines",
                to="payment.receipt",
            ),
        ),
    ]
