# Generated by Django 5.1.14 on 2026-01-24 18:11

import comunicat.utils.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "title",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                ("date", models.DateField()),
                (
                    "module",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "ORG"), (20, "TOWERS")]
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
