# Generated by Django 5.1.7 on 2025-03-22 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bylaws',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('module', models.PositiveSmallIntegerField(choices=[(10, 'ORG'), (20, 'TOWERS')])),
                ('date', models.DateField()),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
