# Generated by Django 5.1.7 on 2025-03-22 14:46

import comunicat.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_bylaws'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bylaws',
            options={'verbose_name': 'bylaws', 'verbose_name_plural': 'bylaws'},
        ),
        migrations.RemoveField(
            model_name='bylaws',
            name='body',
        ),
        migrations.AddField(
            model_name='bylaws',
            name='content',
            field=models.JSONField(default=comunicat.utils.models.language_field_default),
        ),
    ]
