# Generated by Django 5.1.14 on 2026-01-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0004_role_name_plural"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="date_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
