# Generated by Django 5.1.14 on 2026-01-24 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_groups(apps, schema_editor):
    Team = apps.get_model("legal", "Team")
    Group = apps.get_model("legal", "Group")

    group_creates = {}
    team_updates = []

    for team_obj in Team.objects.all():
        group_key = (team_obj.module, team_obj.date_from, team_obj.date_to)
        group_obj = group_creates.get(group_key)
        if not group_obj:
            group_obj = Group(
                module=team_obj.module,
                date_from=team_obj.date_from,
                date_to=team_obj.date_to,
            )
            group_creates[group_key] = group_obj

        team_obj.group = group_obj
        team_updates.append(team_obj)

    if group_creates:
        Group.objects.bulk_create(group_creates.values())

    if team_updates:
        Team.objects.bulk_update(team_updates, fields=("group",))


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0005_member_date_from_member_date_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "module",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "ORG"), (20, "TOWERS")]
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="team",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="legal.group",
            ),
        ),
        migrations.RunPython(create_groups, migrations.RunPython.noop),
    ]
