# Generated by Django 5.1.14 on 2026-01-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0006_group_team_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="date_from",
        ),
        migrations.RemoveField(
            model_name="team",
            name="date_to",
        ),
        migrations.RemoveField(
            model_name="team",
            name="module",
        ),
        migrations.AlterField(
            model_name="team",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="legal.group",
            ),
        ),
    ]
