# Generated by Django 5.1.15 on 2026-05-15 09:09

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0007_remove_team_date_from_remove_team_date_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="legal/member/picture/",
                verbose_name="Image",
            ),
        ),
    ]
