# Generated by Django 5.2.16 on 2026-07-24 11:17

import legal.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0008_alter_member_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "BOARD"),
                    (20, "TECHNICAL"),
                    (30, "MUSICIANS"),
                    (40, "COMMISSION"),
                    (50, "ELECTION"),
                    (60, "AUDITING"),
                ],
                default=legal.enums.TeamType["BOARD"],
            ),
        ),
    ]
