# Generated by Django 5.1.8 on 2025-07-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArticleImage",
            new_name="ProductImage",
        ),
    ]
