# Generated by Django 5.1.8 on 2025-07-05 11:51

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_articleimage_productimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StockArticle",
            new_name="StockProduct",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="picture",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to="product/image/picture/", verbose_name="Image"
            ),
        ),
    ]
