# Generated by Django 5.1.8 on 2025-07-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0031_receipt_entity_part_2"),
        ("product", "0003_rename_stockarticle_stockproduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockorder",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_orders",
                to="payment.receipt",
            ),
        ),
        migrations.AlterField(
            model_name="stockproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="product.stockorder",
            ),
        ),
        migrations.AlterField(
            model_name="stockproduct",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stocks",
                to="product.productsize",
            ),
        ),
    ]
