# Generated by Django 5.1.11 on 2025-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_productprice_amount_currency_productmodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodule",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
    ]
