# Generated by Django 5.1.11 on 2025-08-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_productmodule_is_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
