# Generated by Django 5.2.16 on 2026-07-26 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_productaccounts_product_accounts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productaccounts",
            options={
                "verbose_name": "product accounts",
                "verbose_name_plural": "product accounts",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="accounts",
        ),
        migrations.AddField(
            model_name="productaccounts",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="product.product",
            ),
        ),
    ]
