# Generated by Django 5.2.16 on 2026-07-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_alter_productaccounts_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productaccounts",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="product.product",
            ),
        ),
    ]
