# Generated by Django 5.2.16 on 2026-08-02 13:31

import comunicat.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_alter_productaccounts_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsize",
            name="description",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
    ]
