# Generated by Django 5.2.16 on 2026-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_reservationorder_reservationproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationorder",
            name="notes",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="stockorder",
            name="notes",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
