# Generated by Django 5.2.17 on 2026-10-03 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppleWalletRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("device_library_id", models.CharField(max_length=255)),
                ("pass_type_id", models.CharField(max_length=255)),
                ("serial_number", models.CharField(max_length=255)),
                ("push_token", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("pass_type_id", "serial_number")},
            },
        ),
    ]
