# Generated by Django 5.2.17 on 2026-10-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration", "0002_applewalletregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="applewalletregistration",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
