from phonenumbers.phonenumberutil import country_code_for_region

from comunicat.enums import Module

from django.conf import settings

from legal.enums import PermissionLevel

CODE_NAME_BY_MODULE = {
    Module.ORG: settings.MODULE_ORG_CODE_NAME,
    Module.TOWERS: settings.MODULE_TOWERS_CODE_NAME,
}

SHORT_NAME_BY_MODULE = {
    Module.ORG: settings.MODULE_ORG_SHORT_NAME,
    Module.TOWERS: settings.MODULE_TOWERS_SHORT_NAME,
}

DOMAIN_BY_MODULE = {
    Module.ORG: settings.MODULE_ORG_DOMAIN,
    Module.TOWERS: settings.MODULE_TOWERS_DOMAIN,
}

GOOGLE_ENABLED_BY_MODULE = {
    Module.ORG: {
        "calendar": settings.MODULE_ORG_GOOGLE_CALENDAR_ENABLED,
        "photos": settings.MODULE_ORG_GOOGLE_PHOTOS_ENABLED,
    },
    Module.TOWERS: {
        "calendar": settings.MODULE_TOWERS_GOOGLE_CALENDAR_ENABLED,
        "photos": settings.MODULE_TOWERS_GOOGLE_PHOTOS_ENABLED,
    },
}

PERMISSIONS_BY_LEVEL = {
    "event": {
        "registration": {
            "list": PermissionLevel.ADMIN,
        }
    },
    "user": {
        "user": {
            "list": PermissionLevel.ADMIN,
        }
    },
    "product": {
        "product": {
            "list": PermissionLevel.ADMIN,
        }
    },
}


COUNTRY_LIST = [
    ("Afghanistan", "Afganistan", "Afghanistan", "AFG", False),
    ("Albania", "Albània", "Albanien", "ALB", False),
    ("Algeria", "Algèria", "Algeriet", "DZA", False),
    ("American Samoa", "Samoa Nord-americana", "Amerikanska Samoa", "ASM", False),
    ("Andorra", "Andorra", "Andorra", "AND", False),
    ("Angola", "Angola", "Angola", "AGO", False),
    ("Anguilla", "Anguilla", "Anguilla", "AIA", False),
    ("Antarctica", "Antàrtida", "Antarktis", "ATA", False),
    ("Antigua and Barbuda", "Antigua i Barbuda", "Antigua och Barbuda", "ATG", False),
    ("Argentina", "Argentina", "Argentina", "ARG", False),
    ("Armenia", "Armènia", "Armenien", "ARM", False),
    ("Aruba", "Aruba", "Aruba", "ABW", False),
    ("Australia", "Austràlia", "Australien", "AUS", False),
    ("Austria", "Àustria", "Österrike", "AUT", False),
    ("Azerbaijan", "Azerbaidjan", "Azerbajdzjan", "AZE", False),
    ("Bahamas (the)", "Bahames (les)", "Bahamas (den)", "BHS", False),
    ("Bahrain", "Bahrain", "Bahrain", "BHR", False),
    ("Bangladesh", "Bangla Desh", "Bangladesh", "BGD", False),
    ("Barbados", "Barbados", "Barbados", "BRB", False),
    ("Belarus", "Bielorússia", "Belarus", "BLR", False),
    ("Belgium", "Bèlgica", "Belgien", "BEL", False),
    ("Belize", "Belize", "Belize", "BLZ", False),
    ("Benin", "Benín", "Benin", "BEN", False),
    ("Bermuda", "Bermudes", "Bermuda", "BMU", False),
    ("Bhutan", "Butan", "Bhutan", "BTN", False),
    (
        "Bolivia (Plurinational State of)",
        "Bolívia (Estat Plurinacional de)",
        "Bolivia (plurinationell stat)",
        "BOL",
        False,
    ),
    (
        "Bonaire, Sint Eustatius and Saba",
        "Bonaire, Sint Eustatius i Saba",
        "Bonaire, Sint Eustatius och Saba",
        "BES",
        False,
    ),
    (
        "Bosnia and Herzegovina",
        "Bòsnia i Hercegovina",
        "Bosnien och Hercegovina",
        "BIH",
        False,
    ),
    ("Botswana", "Botswana", "Botswana", "BWA", False),
    ("Bouvet Island", "Illa Bouvet", "Bouvetön", "BVT", False),
    ("Brazil", "Brasil", "Brasilien", "BRA", False),
    (
        "British Indian Ocean Territory (the)",
        "Territori Britànic de l'Oceà Índic (el)",
        "Brittiska territoriet i Indiska oceanen (den)",
        "IOT",
        False,
    ),
    ("Brunei Darussalam", "Brunei Darussalam", "Brunei Darussalam", "BRN", False),
    ("Bulgaria", "Bulgària", "Bulgarien", "BGR", False),
    ("Burkina Faso", "Burkina Faso", "Burkina Faso", "BFA", False),
    ("Burundi", "Burundi", "Burundi", "BDI", False),
    ("Cabo Verde", "Cap Verd", "Cabo Verde", "CPV", False),
    ("Cambodia", "Cambodja", "Kambodja", "KHM", False),
    ("Cameroon", "Camerun", "Kamerun", "CMR", False),
    ("Canada", "Canadà", "Kanada", "CAN", False),
    ("Cayman Islands (the)", "Illes Caiman (les)", "Caymanöarna (den)", "CYM", False),
    (
        "Central African Republic (the)",
        "República Centreafricana (la)",
        "Centralafrikanska republiken (den)",
        "CAF",
        False,
    ),
    ("Chad", "Txad", "Tchad", "TCD", False),
    ("Chile", "Xile", "Chile", "CHL", False),
    ("China", "Xina", "Kina", "CHN", False),
    ("Christmas Island", "Illa de Nadal", "Julön", "CXR", False),
    (
        "Cocos (Keeling) Islands (the)",
        "Illes Cocos (Keeling)",
        "Cocos (Keeling) Islands (the)",
        "CCK",
        False,
    ),
    ("Colombia", "Colòmbia", "Colombia", "COL", False),
    ("Comoros (the)", "Comores (les)", "Komorerna (den)", "COM", False),
    (
        "Congo (the Democratic Republic of the)",
        "Congo (República Democràtica del)",
        "Kongo (Demokratiska republiken)",
        "COD",
        False,
    ),
    ("Congo (the)", "Congo (el)", "Kongo (den)", "COG", False),
    ("Cook Islands (the)", "Illes Cook (les)", "Cooköarna (den)", "COK", False),
    ("Costa Rica", "Costa Rica", "Costa Rica", "CRI", False),
    ("Croatia", "Croàcia", "Kroatien", "HRV", False),
    ("Cuba", "Cuba", "Kuba", "CUB", False),
    ("Curaçao", "Curaçao", "Curaçao", "CUW", False),
    ("Cyprus", "Xipre", "Cypern", "CYP", False),
    ("Czechia", "Txeca", "Tjeckien", "CZE", False),
    ("Côte d'Ivoire", "Costa d'Ivori", "Elfenbenskusten", "CIV", False),
    ("Denmark", "Dinamarca", "Danmark", "DNK", False),
    ("Djibouti", "Djibouti", "Djibouti", "DJI", False),
    ("Dominica", "Dominica", "Dominica", "DMA", False),
    (
        "Dominican Republic (the)",
        "República Dominicana (la)",
        "Dominikanska republiken (den)",
        "DOM",
        False,
    ),
    ("Ecuador", "Equador", "Ecuador", "ECU", False),
    ("Egypt", "Egipte", "Egypten", "EGY", False),
    ("El Salvador", "El Salvador", "El Salvador", "SLV", False),
    ("Equatorial Guinea", "Guinea Equatorial", "Ekvatorialguinea", "GNQ", False),
    ("Eritrea", "Eritrea", "Eritrea", "ERI", False),
    ("Estonia", "Estònia", "Estland", "EST", False),
    ("Eswatini", "Eswatini", "Eswatini", "SWZ", False),
    ("Ethiopia", "Etiòpia", "Etiopien", "ETH", False),
    (
        "Falkland Islands (the) [Malvinas]",
        "Illes Falkland (les) [Malvines]",
        "Falklandsöarna (den) [Malvinas]",
        "FLK",
        False,
    ),
    ("Faroe Islands (the)", "Illes Fèroe", "Färöarna", "FRO", False),
    ("Fiji", "Fiji", "Fiji", "FJI", False),
    ("Finland", "Finlàndia", "Finland", "FIN", False),
    ("France", "França", "Frankrike", "FRA", False),
    ("French Guiana", "Guaiana Francesa", "Franska Guyana", "GUF", False),
    ("French Polynesia", "Polinèsia Francesa", "Franska Polynesien", "PYF", False),
    (
        "French Southern Territories (the)",
        "Territoris del Sud francesos (els)",
        "Franska sydterritorierna (den)",
        "ATF",
        False,
    ),
    ("Gabon", "Gabon", "Gabon", "GAB", False),
    ("Gambia (the)", "Gàmbia (la)", "Gambia (den)", "GMB", False),
    ("Georgia", "Geòrgia", "Georgien", "GEO", False),
    ("Germany", "Alemanya", "Tyskland", "DEU", False),
    ("Ghana", "Ghana", "Ghana", "GHA", False),
    ("Gibraltar", "Gibraltar", "Gibraltar", "GIB", False),
    ("Greece", "Grècia", "Grekland", "GRC", False),
    ("Greenland", "Groenlàndia", "Grönland", "GRL", False),
    ("Grenada", "Grenada", "Grenada", "GRD", False),
    ("Guadeloupe", "Guadalupe", "Guadeloupe", "GLP", False),
    ("Guam", "Guam", "Guam", "GUM", False),
    ("Guatemala", "Guatemala", "Guatemala", "GTM", False),
    ("Guernsey", "Guernsey", "Guernsey", "GGY", False),
    ("Guinea", "Guinea", "Guinea", "GIN", False),
    ("Guinea-Bissau", "Guinea-Bissau", "Guinea-Bissau", "GNB", False),
    ("Guyana", "Guyana", "Guyana", "GUY", False),
    ("Haiti", "Haití", "Haiti", "HTI", False),
    (
        "Heard Island and McDonald Islands",
        "Illa Heard i Illes McDonald",
        "Heard- och McDonaldöarna",
        "HMD",
        False,
    ),
    ("Holy See (the)", "Santa Seu", "Heliga stolen (the)", "VAT", False),
    ("Honduras", "Hondures", "Honduras", "HND", False),
    ("Hong Kong", "Hong Kong", "Hongkong", "HKG", False),
    ("Hungary", "Hongria", "Ungern", "HUN", False),
    ("Iceland", "Islàndia", "Island", "ISL", False),
    ("India", "Índia", "Indien", "IND", False),
    ("Indonesia", "Indonèsia", "Indonesien", "IDN", False),
    (
        "Iran (Islamic Republic of)",
        "Iran (República Islàmica)",
        "Iran (Islamiska republiken)",
        "IRN",
        False,
    ),
    ("Iraq", "Iraq", "Irak", "IRQ", False),
    ("Ireland", "Irlanda", "Irland", "IRL", False),
    ("Isle of Man", "Illa de Man", "Isle of Man", "IMN", False),
    ("Israel", "Israel", "Israel", "ISR", False),
    ("Italy", "Itàlia", "Italien", "ITA", False),
    ("Jamaica", "Jamaica", "Jamaica", "JAM", False),
    ("Japan", "Japó", "Japan", "JPN", False),
    ("Jersey", "Jersey", "Jersey", "JEY", False),
    ("Jordan", "Jordània", "Jordanien", "JOR", False),
    ("Kazakhstan", "Kazakhstan", "Kazakstan", "KAZ", False),
    ("Kenya", "Kenya", "Kenya", "KEN", False),
    ("Kiribati", "Kiribati", "Kiribati", "KIR", False),
    (
        "Korea (the Democratic People's Republic of)",
        "Corea (República Popular Democràtica)",
        "Korea (Demokratiska folkrepubliken)",
        "PRK",
        False,
    ),
    (
        "Korea (the Republic of)",
        "Corea (República)",
        "Korea (Republiken)",
        "KOR",
        False,
    ),
    ("Kuwait", "Kuwait", "Kuwait", "KWT", False),
    ("Kyrgyzstan", "Kirguizistan", "Kirgizistan", "KGZ", False),
    (
        "Lao People's Democratic Republic (the)",
        "República Democràtica Popular de Laos",
        "Laos (Demokratiska folkrepubliken)",
        "LAO",
        False,
    ),
    ("Latvia", "Letònia", "Lettland", "LVA", False),
    ("Lebanon", "Líban", "Libanon", "LBN", False),
    ("Lesotho", "Lesotho", "Lesotho", "LSO", False),
    ("Liberia", "Libèria", "Liberia", "LBR", False),
    ("Libya", "Líbia", "Libyen", "LBY", False),
    ("Liechtenstein", "Liechtenstein", "Liechtenstein", "LIE", False),
    ("Lithuania", "Lituània", "Litauen", "LTU", False),
    ("Luxembourg", "Luxemburg", "Luxemburg", "LUX", False),
    ("Macao", "Macau", "Macao", "MAC", False),
    ("Madagascar", "Madagascar", "Madagaskar", "MDG", False),
    ("Malawi", "Malawi", "Malawi", "MWI", False),
    ("Malaysia", "Malàisia", "Malaysia", "MYS", False),
    ("Maldives", "Maldives", "Maldiverna", "MDV", False),
    ("Mali", "Mali", "Mali", "MLI", False),
    ("Malta", "Malta", "Malta", "MLT", False),
    ("Marshall Islands (the)", "Illes Marshall", "Marshallöarna (den)", "MHL", False),
    ("Martinique", "Martinica", "Martinique", "MTQ", False),
    ("Mauritania", "Mauritània", "Mauretanien", "MRT", False),
    ("Mauritius", "Maurici", "Mauritius", "MUS", False),
    ("Mayotte", "Mayotte", "Mayotte", "MYT", False),
    ("Mexico", "Mèxic", "Mexiko", "MEX", False),
    (
        "Micronesia (Federated States of)",
        "Micronèsia (Estats Federats de)",
        "Mikronesien (federerade stater)",
        "FSM",
        False,
    ),
    (
        "Moldova (the Republic of)",
        "Moldàvia (República de)",
        "Moldavien (Republiken)",
        "MDA",
        False,
    ),
    ("Monaco", "Mònaco", "Monaco", "MCO", False),
    ("Mongolia", "Mongòlia", "Mongoliet", "MNG", False),
    ("Montenegro", "Montenegro", "Montenegro", "MNE", False),
    ("Montserrat", "Montserrat", "Montserrat", "MSR", False),
    ("Morocco", "Marroc", "Marocko", "MAR", False),
    ("Mozambique", "Moçambic", "Moçambique", "MOZ", False),
    ("Myanmar", "Myanmar", "Myanmar", "MMR", False),
    ("Namibia", "Namíbia", "Namibia", "NAM", False),
    ("Nauru", "Nauru", "Nauru", "NRU", False),
    ("Nepal", "Nepal", "Nepal", "NPL", False),
    ("Netherlands (the)", "Països Baixos", "Nederländerna (den)", "NLD", False),
    ("New Caledonia", "Nova Caledònia", "Nya Kaledonien", "NCL", False),
    ("New Zealand", "Nova Zelanda", "Nya Zeeland", "NZL", False),
    ("Nicaragua", "Nicaragua", "Nicaragua", "NIC", False),
    ("Niger (the)", "Níger", "Niger (den)", "NER", False),
    ("Nigeria", "Nigèria", "Nigeria", "NGA", False),
    ("Niue", "Niue", "Niue", "NIU", False),
    ("Norfolk Island", "Illa Norfolk", "Norfolkön", "NFK", False),
    (
        "Northern Mariana Islands (the)",
        "Illes Mariannes del Nord",
        "Nordmarianerna (den)",
        "MNP",
        False,
    ),
    ("Norway", "Noruega", "Norge", "NOR", False),
    ("Oman", "Oman", "Oman", "OMN", False),
    ("Pakistan", "Pakistan", "Pakistan", "PAK", False),
    ("Palau", "Palau", "Palau", "PLW", False),
    ("Palestine, State of", "Estat de Palestina", "Palestina, staten", "PSE", False),
    ("Panama", "Panamà", "Panama", "PAN", False),
    ("Papua New Guinea", "Papua Nova Guinea", "Papua Nya Guinea", "PNG", False),
    ("Paraguay", "Paraguai", "Paraguay", "PRY", False),
    ("Peru", "Perú", "Peru", "PER", False),
    ("Philippines (the)", "Filipines", "Filippinerna", "PHL", False),
    ("Pitcairn", "Pitcairn", "Pitcairn", "PCN", False),
    ("Poland", "Polònia", "Polen", "POL", False),
    ("Portugal", "Portugal", "Portugal", "PRT", False),
    ("Puerto Rico", "Puerto Rico", "Puerto Rico", "PRI", False),
    ("Qatar", "Qatar", "Qatar", "QAT", False),
    (
        "Republic of North Macedonia",
        "República de Macedònia del Nord",
        "Republiken Nordmakedonien",
        "MKD",
        False,
    ),
    ("Romania", "Romania", "Rumänien", "ROU", False),
    ("Russian Federation (the)", "Federació Russa", "Ryska federationen", "RUS", False),
    ("Rwanda", "Ruanda", "Rwanda", "RWA", False),
    ("Réunion", "Reunió", "Réunion", "REU", False),
    ("Saint Barthélemy", "Saint Barthélemy", "Saint Barthélemy", "BLM", False),
    (
        "Saint Helena, Ascension and Tristan da Cunha",
        "Santa Helena, Ascensió i Tristan da Cunha",
        "Saint Helena, Ascension och Tristan da Cunha",
        "SHN",
        False,
    ),
    (
        "Saint Kitts and Nevis",
        "Saint Kitts i Nevis",
        "Saint Kitts och Nevis",
        "KNA",
        False,
    ),
    ("Saint Lucia", "Santa Llúcia", "Saint Lucia", "LCA", False),
    (
        "Saint Martin (French part)",
        "Saint Martin (part francesa)",
        "Saint Martin (franska delen)",
        "MAF",
        False,
    ),
    (
        "Saint Pierre and Miquelon",
        "Saint Pierre i Miquelon",
        "Saint Pierre och Miquelon",
        "SPM",
        False,
    ),
    (
        "Saint Vincent and the Grenadines",
        "Saint Vincent i les Grenadines",
        "Saint Vincent och Grenadinerna",
        "VCT",
        False,
    ),
    ("Samoa", "Samoa", "Samoa", "WSM", False),
    ("San Marino", "San Marino", "San Marino", "SMR", False),
    (
        "Sao Tome and Principe",
        "São Tomé i Príncipe",
        "Sao Tomé och Principe",
        "STP",
        False,
    ),
    ("Saudi Arabia", "Aràbia Saudita", "Saudiarabien", "SAU", False),
    ("Senegal", "Senegal", "Senegal", "SEN", False),
    ("Serbia", "Sèrbia", "Serbien", "SRB", False),
    ("Seychelles", "Seychelles", "Seychellerna", "SYC", False),
    ("Sierra Leone", "Sierra Leone", "Sierra Leone", "SLE", False),
    ("Singapore", "Singapur", "Singapore", "SGP", False),
    (
        "Sint Maarten (Dutch part)",
        "Sint Maarten (part neerlandesa)",
        "Sint Maarten (nederländska delen)",
        "SXM",
        False,
    ),
    ("Slovakia", "Eslovàquia", "Slovakien", "SVK", False),
    ("Slovenia", "Eslovènia", "Slovenien", "SVN", False),
    ("Solomon Islands", "Illes Salomó", "Salomonöarna", "SLB", False),
    ("Somalia", "Somàlia", "Somalia", "SOM", False),
    ("South Africa", "Sud-àfrica", "Sydafrika", "ZAF", False),
    (
        "South Georgia and the South Sandwich Islands",
        "Geòrgia del Sud i les Illes Sandwich del Sud",
        "Sydgeorgien och Sydsandwichöarna",
        "SGS",
        False,
    ),
    ("South Sudan", "Sudan del Sud", "Sydsudan", "SSD", False),
    ("Spain", "Espanya", "Spanien", "ESP", False),
    ("Sri Lanka", "Sri Lanka", "Sri Lanka", "LKA", False),
    ("Sudan (the)", "Sudan", "Sudan (den)", "SDN", False),
    ("Suriname", "Surinam", "Surinam", "SUR", False),
    (
        "Svalbard and Jan Mayen",
        "Svalbard i Jan Mayen",
        "Svalbard och Jan Mayen",
        "SJM",
        False,
    ),
    ("Sweden", "Suècia", "Sverige", "SWE", True),
    ("Switzerland", "Suïssa", "Schweiz", "CHE", False),
    (
        "Syrian Arab Republic",
        "República Àrab Siriana",
        "Syrien Arabrepubliken",
        "SYR",
        False,
    ),
    ("Taiwan", "Taiwan", "Taiwan (provinsen Kina)", "TWN", False),
    ("Tajikistan", "Tadjikistan", "Tadzjikistan", "TJK", False),
    (
        "Tanzania, United Republic of",
        "Tanzània, República Unida de",
        "Tanzania, Förenade republiken",
        "TZA",
        False,
    ),
    ("Thailand", "Tailàndia", "Thailand", "THA", False),
    ("Timor-Leste", "Timor Oriental", "Östtimor", "TLS", False),
    ("Togo", "Togo", "Togo", "TGO", False),
    ("Tokelau", "Tokelau", "Tokelau", "TKL", False),
    ("Tonga", "Tonga", "Tonga", "TON", False),
    ("Trinidad and Tobago", "Trinitat i Tobago", "Trinidad och Tobago", "TTO", False),
    ("Tunisia", "Tunísia", "Tunisien", "TUN", False),
    ("Turkey", "Turquia", "Turkiet", "TUR", False),
    ("Turkmenistan", "Turkmenistan", "Turkmenistan", "TKM", False),
    (
        "Turks and Caicos Islands (the)",
        "Illes Turks i Caicos",
        "Turks- och Caicosöarna (den)",
        "TCA",
        False,
    ),
    ("Tuvalu", "Tuvalu", "Tuvalu", "TUV", False),
    ("Uganda", "Uganda", "Uganda", "UGA", False),
    ("Ukraine", "Ucraïna", "Ukraina", "UKR", False),
    (
        "United Arab Emirates (the)",
        "Emirats Àrabs Units",
        "Förenade Arabemiraten (den)",
        "ARE",
        False,
    ),
    (
        "United Kingdom of Great Britain and Northern Ireland (the)",
        "Regne Unit de la Gran Bretanya i Irlanda del Nord",
        "Förenade kungariket Storbritannien och Nordirland (den)",
        "GBR",
        False,
    ),
    (
        "United States Minor Outlying Islands (the)",
        "Illes Perifèriques Menors dels Estats Units",
        "Förenta staternas mindre avlägsna öar (den)",
        "UMI",
        False,
    ),
    (
        "United States of America (the)",
        "Estats Units d'Amèrica",
        "Amerikas förenta stater (den)",
        "USA",
        False,
    ),
    ("Uruguay", "Uruguai", "Uruguay", "URY", False),
    ("Uzbekistan", "Uzbekistan", "Uzbekistan", "UZB", False),
    ("Vanuatu", "Vanuatu", "Vanuatu", "VUT", False),
    (
        "Venezuela (Bolivarian Republic of)",
        "Veneçuela (República Bolivariana de)",
        "Venezuela (Bolivariska republiken)",
        "VEN",
        False,
    ),
    ("Viet Nam", "Vietnam", "Vietnam", "VNM", False),
    (
        "Virgin Islands (British)",
        "Illes Verges Britàniques",
        "Jungfruöarna (brittiska)",
        "VGB",
        False,
    ),
    (
        "Virgin Islands (U.S.)",
        "Illes Verges Nord-americanes",
        "Jungfruöarna (USA)",
        "VIR",
        False,
    ),
    ("Wallis and Futuna", "Wallis i Futuna", "Wallis och Futuna", "WLF", False),
    ("Western Sahara", "Sàhara Occidental", "Västsahara", "ESH", False),
    ("Yemen", "Iemen", "Jemen", "YEM", False),
    ("Zambia", "Zàmbia", "Zambia", "ZMB", False),
    ("Zimbabwe", "Zimbàbue", "Zimbabwe", "ZWE", False),
    ("Åland Islands", "Illes Åland", "Åland", "ALA", False),
    ("Catalan Countries", "Països Catalans", "Katalanska länderna", "PCA", True),
]

REGION_LIST = {
    "PCA": [
        ("Catalonia", "Catalunya", "Katalonien", "CAT"),
        ("Valencian country", "País Valencià", "Valencianska landet", "VAL"),
        ("Balearic Islands", "Illes Balears", "Baleariska öarna", "BAL"),
        (
            "Franja de Ponent [Aragó]",
            "Franja de Ponent [Aragó]",
            "Franja de Ponent [Aragó]",
            "FPO",
        ),
        (
            "El Carxe [Region of Murcia]",
            "El Carxe [Regió de Múrcia]",
            "El Carxe [Murcia]",
            "CAR",
        ),
        (
            "Northern Catalonia [Pirineus Orientals]",
            "Catalunya del Nord [Pirineus Orientals]",
            "Norra Katalonien [Pirineus Orientals]",
            "CNO",
        ),
        (
            "Alguer [Sardinia]",
            "Alguer (l’) [Sardenya]",
            "Alguer (l’) [Sardinien]",
            "ALG",
        ),
    ],
    "SWE": [
        ("Blekinge län", "Blekinge län", "Blekinge län", "K"),
        ("Dalarnas län", "Dalarnas län", "Dalarnas län", "W"),
        ("Gotlands län", "Gotlands län", "Gotlands län", "I"),
        ("Gävleborgs län", "Gävleborgs län", "Gävleborgs län", "X"),
        ("Hallands län", "Hallands län", "Hallands län", "N"),
        ("Jämtlands län", "Jämtlands län", "Jämtlands län", "Z"),
        ("Jönköpings län", "Jönköpings län", "Jönköpings län", "F"),
        ("Kalmar län", "Kalmar län", "Kalmar län", "H"),
        ("Kronobergs län", "Kronobergs län", "Kronobergs län", "G"),
        ("Norrbottens län", "Norrbottens län", "Norrbottens län", "BD"),
        ("Skåne län", "Skåne län", "Skåne län", "M"),
        ("Stockholms län", "Stockholms län", "Stockholms län", "AB"),
        ("Södermanlands län", "Södermanlands län", "Södermanlands län", "D"),
        ("Uppsala län", "Uppsala län", "Uppsala län", "C"),
        ("Värmlands län", "Värmlands län", "Värmlands län", "S"),
        ("Västerbottens län", "Västerbottens län", "Västerbottens län", "AC"),
        ("Västernorrlands län", "Västernorrlands län", "Västernorrlands län", "Y"),
        ("Västmanlands län", "Västmanlands län", "Västmanlands län", "U"),
        ("Västra Götalands län", "Västra Götalands län", "Västra Götalands län", "O"),
        ("Örebro län", "Örebro län", "Örebro län", "T"),
        ("Östergötlands län", "Östergötlands län", "Östergötlands län", "E"),
    ],
}

# TODO: Redo this a bit more standard for other languages
COUNTRY_BY_CODE = {
    country_code: {
        "name": {"en": country_en, "ca": country_ca, "sv": country_sv},
        "is_starred": is_starred,
    }
    for country_en, country_ca, country_sv, country_code, is_starred in COUNTRY_LIST
}

REGION_BY_COUNTRY_AND_CODE = {
    country_code: {
        region_code: {"name": {"en": region_en, "ca": region_ca, "sv": region_sv}}
        for region_en, region_ca, region_sv, region_code in regions
    }
    for country_code, regions in REGION_LIST.items()
}
