from comunicat.settings import *  # noqa: F401,F403

SECRET_KEY = "2x9%{O91)OE>F#+ZzGbof8mht+flJ[[O"

MODULE_ORG_ENABLED = True
MODULE_TOWERS_ENABLED = True
MODULE_ALL_USER_FIELDS = ["phone"]
MODULE_ALL_USER_MINIMUM_AGE = 16
MODULE_ALL_MEMBERSHIP_REQUIRED = [Module.ORG]
MODULE_ALL_MEMBERSHIP_START_DATES = [[1, 1], [1, 7]]
MODULE_ALL_MEMBERSHIP_CONFIG = [[1, 12], [2, 12]]
MODULE_ALL_MEMBERSHIP_RENEW_DAYS = 28
MODULE_ALL_CURRENCY = "SEK"
MODULE_ALL_CURRENCIES = ["SEK", "EUR"]
MODULE_ALL_CURRENCY_LOCALE = "sv_SE"
MODULE_ALL_VAT = 0
MODULE_ALL_GOOGLE_CALENDAR_INVITE_MODULES = [Module.TOWERS]
MODULE_ORG_NAME = "Name for ORG"
MODULE_ORG_SHORT_NAME = "Name ORG"
MODULE_ORG_CODE_NAME = "ORG"
MODULE_ORG_DOMAIN = "domain-org.org"
MODULE_ORG_EMAIL_FROM_ADDRESS = "info@domain-org.org"
MODULE_ORG_MEMBERSHIP_CONFIG = [[1, 150], [2, 250]]
MODULE_ORG_MEMBERSHIP_ACCOUNT_CONFIG = [[1, 1010], [2, 1011]]
MODULE_TOWERS_NAME = "Name for TOWERS"
MODULE_TOWERS_SHORT_NAME = "Name TOWERS"
MODULE_TOWERS_CODE_NAME = "TOWERS"
MODULE_TOWERS_DOMAIN = "domain-towers.org"
MODULE_TOWERS_USER_FIELDS = ["alias", "height_shoulders", "height_arms"]
MODULE_TOWERS_EMAIL_FROM_ADDRESS = "info@domain-towers.org"
MODULE_TOWERS_MEMBERSHIP_CONFIG = [[1, 250], [2, 450]]
MODULE_TOWERS_MEMBERSHIP_ACCOUNT_CONFIG = [[1, 2010], [2, 2011]]
MODULE_TOWERS_NOTIFY_EVENT_SIGNUP_TIME = {"day_of_week": "mon", "hour": 10, "minute": 0}
MODULE_TOWERS_NOTIFY_EVENT_SIGNUP_RANGE_DAYS = [0, 30]
MODULE_TOWERS_GOOGLE_CALENDAR_ENABLED = True
MODULE_TOWERS_GOOGLE_PHOTOS_ENABLED = True

# Celery

CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True

# Email

EMAIL_PROVIDER = None

# Logging

LOGGING["loggers"]["celery.app.trace"] = {  # noqa: F405
    "handlers": ["console"],
    "level": "ERROR",
    "propagate": False,
}
