# Generated by Django 5.1.5 on 2025-01-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_email_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='locale',
            field=models.CharField(default='en', max_length=5),
            preserve_default=False,
        ),
    ]
