# Generated by Django 5.1.7 on 2025-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0004_email_email_alter_email_module_alter_email_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "REGISTER"),
                    (11, "PASSWORD"),
                    (12, "WELCOME"),
                    (13, "IMPORTED"),
                    (20, "FAMILY_INVITE"),
                ]
            ),
        ),
    ]
