# Generated by Django 5.1.11 on 2025-07-28 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0006_alter_email_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageSlack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("channel_id", models.CharField(max_length=255)),
                ("message_id", models.CharField(max_length=255)),
                (
                    "type",
                    models.PositiveSmallIntegerField(choices=[(50, "ORDER_CREATED")]),
                ),
                (
                    "module",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "ORG"), (20, "TOWERS")]
                    ),
                ),
                ("locale", models.CharField(max_length=5)),
                ("blocks", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="email",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "REGISTER"),
                    (11, "PASSWORD"),
                    (12, "WELCOME"),
                    (13, "IMPORTED"),
                    (20, "FAMILY_INVITE"),
                    (30, "EVENT_SIGNUP"),
                    (40, "MEMBERSHIP_RENEW"),
                    (41, "MEMBERSHIP_EXPIRED"),
                    (50, "ORDER_CREATED"),
                ]
            ),
        ),
    ]
