# Generated by Django 5.1.14 on 2025-11-19 21:11

import comunicat.utils.models
import django.db.models.deletion
import notify.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0007_messageslack_alter_email_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "subject",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                (
                    "body",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="email",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "DRAFT"), (20, "SENT")],
                default=notify.enums.EmailStatus["SENT"],
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "GENERAL"),
                    (10, "REGISTER"),
                    (11, "PASSWORD"),
                    (12, "WELCOME"),
                    (13, "IMPORTED"),
                    (20, "FAMILY_INVITE"),
                    (30, "EVENT_SIGNUP"),
                    (40, "MEMBERSHIP_RENEW"),
                    (41, "MEMBERSHIP_EXPIRED"),
                    (42, "MEMBERSHIP_PAID"),
                    (43, "MEMBERSHIP_CHECK"),
                    (50, "ORDER_CREATED"),
                    (51, "ORDER_PAID"),
                    (61, "REGISTRATION_PAID"),
                ],
                default=notify.enums.EmailType["GENERAL"],
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails",
                to="notify.emailtemplate",
            ),
        ),
    ]
