# Generated by Django 5.1.14 on 2025-11-19 21:21

import django.db.models.deletion
from django.db import migrations, models, transaction
import payment.api.entity


def set_email_entities(apps, schema_editor):
    Email = apps.get_model("notify", "Email")

    with transaction.atomic():
        for email_obj in Email.objects.select_related("user"):
            entity_obj = payment.api.entity.get_entity_by_key(
                email=email_obj.email or email_obj.user.email
            )
            email_obj.entity_id = entity_obj.id
            email_obj.save(update_fields=("entity_id",))


def set_email_users(apps, schema_editor):
    Email = apps.get_model("notify", "Email")

    with transaction.atomic():
        for email_obj in Email.objects.select_related("entity"):
            email_obj.user_id = email_obj.entity.user_id
            email_obj.email = email_obj.entity.email
            email_obj.save(update_fields=("user_id", "email"))


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0008_emailtemplate_email_status_alter_email_type_and_more"),
        ("payment", "0041_alter_payment_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="payment.entity",
            ),
        ),
        migrations.RunPython(set_email_entities, set_email_users),
    ]
