# Generated by Django 5.1.14 on 2025-11-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0009_email_entity"),
        ("payment", "0041_alter_payment_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="email",
        ),
        migrations.RemoveField(
            model_name="email",
            name="user",
        ),
        migrations.AlterField(
            model_name="email",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="payment.entity",
            ),
        ),
    ]
