# Generated by Django 5.1.14 on 2025-11-19 22:08

import notify.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0010_remove_email_email_remove_email_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "DRAFT"), (20, "SENT")],
                default=notify.enums.EmailStatus["DRAFT"],
            ),
        ),
    ]
