# Generated by Django 5.1.14 on 2025-11-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0011_alter_email_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="button_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="button_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="module",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "ORG"), (20, "TOWERS")], default=10
            ),
            preserve_default=False,
        ),
    ]
