# Generated by Django 5.1.14 on 2025-11-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0012_emailtemplate_button_link_emailtemplate_button_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailtemplate",
            old_name="button_link",
            new_name="button_url",
        ),
    ]
