# Generated by Django 5.1.14 on 2025-11-20 08:46

import comunicat.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0013_rename_button_link_emailtemplate_button_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="button_text",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="button_url",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
    ]
