# Generated by Django 5.1.14 on 2025-11-27 13:18

import django.db.models.deletion
import notify.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0014_alter_emailtemplate_button_text_and_more"),
        ("payment", "0041_alter_payment_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "CREATED"), (20, "REPLIED"), (30, "DELETED")],
                        default=notify.enums.ContactMessageStatus["CREATED"],
                    ),
                ),
                (
                    "module",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "ORG"), (20, "TOWERS")]
                    ),
                ),
                ("message", models.TextField(max_length=1000)),
                ("context", models.JSONField(default=dict)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_messages",
                        to="payment.entity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
