# Generated by Django 5.1.14 on 2025-11-27 13:21

import notify.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0015_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "CREATED"), (20, "REPLIED"), (30, "DELETED")],
                default=notify.enums.ContactMessageStatus["CREATED"],
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "CONTACT"),
                    (20, "BUSINESS_WORKSHOP"),
                    (21, "BUSINESS_PERFORMANCE"),
                ],
                default=notify.enums.ContactMessageType["CONTACT"],
            ),
        ),
    ]
