# Generated by Django 5.1.15 on 2026-05-23 13:16

import comunicat.utils.models
import notify.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0016_contactmessage_status_alter_contactmessage_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "name",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                (
                    "description",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                (
                    "module",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "ORG"), (20, "TOWERS")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "CONTACT"),
                    (20, "BUSINESS_WORKSHOP"),
                    (21, "BUSINESS_PERFORMANCE"),
                    (30, "SIGNUP_LIST"),
                ],
                default=notify.enums.ContactMessageType["CONTACT"],
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "GENERAL"),
                    (10, "REGISTER"),
                    (11, "PASSWORD"),
                    (12, "WELCOME"),
                    (13, "IMPORTED"),
                    (20, "FAMILY_INVITE"),
                    (30, "EVENT_SIGNUP"),
                    (40, "MEMBERSHIP_RENEW"),
                    (41, "MEMBERSHIP_EXPIRED"),
                    (42, "MEMBERSHIP_PAID"),
                    (43, "MEMBERSHIP_CHECK"),
                    (50, "ORDER_CREATED"),
                    (51, "ORDER_PAID"),
                    (61, "REGISTRATION_PAID"),
                    (70, "CONTACT_MESSAGE"),
                    (82, "PAYMENT_PAID"),
                    (92, "COURSE_REGISTRATION_PAID"),
                ],
                default=notify.enums.EmailType["GENERAL"],
            ),
        ),
        migrations.AlterField(
            model_name="messageslack",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (50, "ORDER_CREATED"),
                    (60, "CONTACT_MESSAGE_CREATED"),
                    (71, "REGISTRATION_UPDATED"),
                ]
            ),
        ),
    ]
