# Generated by Django 5.1.15 on 2026-05-23 13:21

from django.db import migrations, models

import notify.enums


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0017_newsletter_alter_contactmessage_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "INTERNAL"), (20, "GOOGLE")],
                default=notify.enums.NewsletterType["INTERNAL"],
            ),
        ),
    ]
