# Generated by Django 5.1.15 on 2026-05-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0018_newsletter_type"),
        ("user", "0027_user_user_user_created_02326c_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="google_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to="user.googlegroupuser",
            ),
        ),
    ]
