# Generated by Django 5.1.15 on 2026-05-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0019_newsletter_google_group"),
        ("user", "0028_alter_userproduct_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="google_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsletters",
                to="user.googlegroup",
            ),
        ),
    ]
