# Generated by Django 5.1.15 on 2026-05-23 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notify", "0017_newsletter_alter_contactmessage_type_and_more"),
        ("payment", "0048_accountevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "GENERAL"),
                            (20, "MEDIA"),
                            (30, "COMMUNICATION"),
                            (40, "NEWSLETTER"),
                        ]
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="payment.entity",
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="notify.newsletter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
