# Generated by Django 5.1.15 on 2026-05-24 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consent", "0001_initial"),
        ("user", "0028_alter_userproduct_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityconsent",
            name="google_group_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to="user.googlegroupuser",
            ),
        ),
        migrations.AlterField(
            model_name="entityconsent",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "MEDIA"),
                    (30, "COMMUNICATION"),
                    (40, "NEWSLETTER"),
                    (50, "HEALTH"),
                ]
            ),
        ),
    ]
