# Generated by Django 5.2.17 on 2026-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consent", "0002_entityconsent_google_group_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityconsent",
            name="module",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "ORG"), (20, "TOWERS")], default=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entityconsent",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "MEDIA"),
                    (30, "COMMUNICATION"),
                    (40, "NEWSLETTER"),
                    (50, "HEALTH"),
                    (60, "SIGNUP"),
                ]
            ),
        ),
    ]
