# Generated by Django 5.1.11 on 2025-08-13 18:48

import comunicat.utils.models
import django.db.models.deletion
import uuid
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "title",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                (
                    "subtitle",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                (
                    "module",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "ORG"), (20, "TOWERS")]
                    ),
                ),
                ("date", models.DateField()),
                (
                    "content",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReleaseImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "picture",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="media/release/image/picture/", verbose_name="Image"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="media.release",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
