# Generated by Django 5.1.11 on 2025-08-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
