# Generated by Django 5.1.11 on 2025-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_alter_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="slug",
            field=models.CharField(default="test", unique=True),
            preserve_default=False,
        ),
    ]
