# syntax=docker/dockerfile:experimental
######################################
# Builder step #######################
######################################
FROM nginx:1.17.8-alpine as build

WORKDIR /pinyator

# Copy the public directory
COPY ./src/ ./pinyator/

# Copy the nginx config file
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

######################################
# Runtime step #######################
######################################
FROM nginx:1.17.8-alpine

WORKDIR /pinyator

# Copy the build directory
COPY --from=build --chown=www-data:www-data /pinyator ./

# Copy the nginx config file
COPY --from=build /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
