# Generated by Django 5.1.7 on 2025-04-18 21:43

import django.core.validators
from django.db import migrations, models

import comunicat.storage
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_alter_document_file_alter_emailattachment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=comunicat.storage.SignedStorage(),
                upload_to=document.models.get_document_file_name,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
