# Generated by Django 5.1.13 on 2025-10-22 11:27

import comunicat.storage
import django.core.validators
import document.enums
import document.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="preview",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="document/document/preview/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                storage=comunicat.storage.SignedStorage(allow_overwrite=True),
                upload_to=document.models.get_document_file_name,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "GENERAL"), (20, "GUIDE"), (30, "RESOURCE")],
                default=document.enums.DocumentType["GENERAL"],
            ),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "REGISTER"),
                    (11, "PASSWORD"),
                    (12, "WELCOME"),
                    (13, "IMPORTED"),
                    (20, "FAMILY_INVITE"),
                    (30, "EVENT_SIGNUP"),
                    (40, "MEMBERSHIP_RENEW"),
                    (41, "MEMBERSHIP_EXPIRED"),
                    (42, "MEMBERSHIP_PAID"),
                    (50, "ORDER_CREATED"),
                    (51, "ORDER_PAID"),
                ]
            ),
        ),
    ]
