# Generated by Django 5.1.13 on 2025-10-22 11:41

import document.models
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "document",
            "0005_document_order_document_preview_alter_document_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="preview",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=document.models.get_document_preview_name,
                verbose_name="Image",
            ),
        ),
    ]
