# Generated by Django 5.1.13 on 2025-10-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0006_alter_document_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="module",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "ORG"), (20, "TOWERS")], default=10
            ),
            preserve_default=False,
        ),
    ]
