# Generated by Django 5.1.13 on 2025-10-22 12:00

import comunicat.storage
import document.models
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0007_document_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="preview",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                storage=comunicat.storage.SignedStorage(allow_overwrite=True),
                upload_to=document.models.get_document_preview_name,
                verbose_name="Image",
            ),
        ),
    ]
