# Generated by Django 5.1.14 on 2025-12-09 20:21

import comunicat.storage
import django.core.validators
import document.enums
import document.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0008_alter_document_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_public",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=document.models.get_document_file_name,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=comunicat.storage.SignedStorage(allow_overwrite=True),
                upload_to=document.models.get_document_file_name,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "GUIDE"),
                    (30, "RESOURCE"),
                    (40, "PRESS"),
                ],
                default=document.enums.DocumentType["GENERAL"],
            ),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "GENERAL"),
                    (10, "REGISTER"),
                    (11, "PASSWORD"),
                    (12, "WELCOME"),
                    (13, "IMPORTED"),
                    (20, "FAMILY_INVITE"),
                    (30, "EVENT_SIGNUP"),
                    (40, "MEMBERSHIP_RENEW"),
                    (41, "MEMBERSHIP_EXPIRED"),
                    (42, "MEMBERSHIP_PAID"),
                    (43, "MEMBERSHIP_CHECK"),
                    (50, "ORDER_CREATED"),
                    (51, "ORDER_PAID"),
                    (61, "REGISTRATION_PAID"),
                    (70, "CONTACT_MESSAGE"),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("file__isnull", False),
                    ("file_public__isnull", False),
                    _connector="OR",
                ),
                name="document_document_file_not_null",
            ),
        ),
    ]
