# Generated by Django 5.1.14 on 2025-12-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0009_document_file_public_alter_document_file_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="document_document_file_not_null",
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("file", ""), ("file", None), _connector="OR"),
                        _negated=True,
                    ),
                    models.Q(
                        models.Q(
                            ("file_public", ""), ("file_public", None), _connector="OR"
                        ),
                        _negated=True,
                    ),
                    _connector="OR",
                ),
                name="document_document_file_not_null",
            ),
        ),
    ]
