# Generated by Django 5.1.14 on 2025-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0010_remove_document_document_document_file_not_null_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
