# Generated by Django 5.1.14 on 2025-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0011_document_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="url_external",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
