# Generated by Django 5.1.15 on 2026-04-26 17:17

import document.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0012_document_url_external"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "GUIDE"),
                    (30, "RESOURCE"),
                    (40, "PRESS"),
                    (50, "NEWSLETTER"),
                ],
                default=document.enums.DocumentType["GENERAL"],
            ),
        ),
        migrations.AlterField(
            model_name="emailattachment",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "GENERAL"),
                    (10, "REGISTER"),
                    (11, "PASSWORD"),
                    (12, "WELCOME"),
                    (13, "IMPORTED"),
                    (20, "FAMILY_INVITE"),
                    (30, "EVENT_SIGNUP"),
                    (40, "MEMBERSHIP_RENEW"),
                    (41, "MEMBERSHIP_EXPIRED"),
                    (42, "MEMBERSHIP_PAID"),
                    (43, "MEMBERSHIP_CHECK"),
                    (50, "ORDER_CREATED"),
                    (51, "ORDER_PAID"),
                    (61, "REGISTRATION_PAID"),
                    (70, "CONTACT_MESSAGE"),
                    (82, "PAYMENT_PAID"),
                    (92, "COURSE_REGISTRATION_PAID"),
                ]
            ),
        ),
    ]
