# Generated by Django 5.1.15 on 2026-05-09 20:39

import document.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0013_alter_document_type_alter_emailattachment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "GUIDE"),
                    (30, "RESOURCE"),
                    (40, "PRESS"),
                    (50, "NEWSLETTER"),
                    (60, "REPORT"),
                ],
                default=document.enums.DocumentType["GENERAL"],
            ),
        ),
    ]
