# Generated by Django 5.2.16 on 2026-07-24 11:17

import document.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0014_alter_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "GENERAL"),
                    (20, "GUIDE"),
                    (30, "RESOURCE"),
                    (40, "PRESS"),
                    (50, "NEWSLETTER"),
                    (60, "REPORT"),
                    (70, "FINANCIAL"),
                ],
                default=document.enums.DocumentType["GENERAL"],
            ),
        ),
    ]
