# Generated by Django 5.1.5 on 2025-01-29 10:21

import django.db.models.deletion
import django.utils.timezone
import user.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_googleuser_towersuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="towersuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="towersuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "MEMBER"), (20, "MANAGER")],
                        default=user.enums.FamilyMemberRole["MEMBER"],
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "REQUESTED"), (20, "ACTIVE"), (30, "DELETED")],
                        default=user.enums.FamilyMemberStatus["REQUESTED"],
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="user.family",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "family")},
            },
        ),
    ]
