# Generated by Django 5.1.5 on 2025-01-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_family_towersuser_created_at_towersuser_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="origin_module",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "TOWERS"), (20, "ORG")], default=10
            ),
            preserve_default=False,
        ),
    ]
