# Generated by Django 5.1.6 on 2025-02-11 12:41

import user.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_familymemberrequest_user_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consent_pictures",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="familymemberrequest",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "REQUESTED"),
                    (20, "ACCEPTED"),
                    (30, "DELETED"),
                    (40, "REJECTED"),
                ],
                default=user.enums.FamilyMemberRequestStatus["REQUESTED"],
            ),
        ),
    ]
