# Generated by Django 5.1.6 on 2025-02-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_preferred_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'family', 'verbose_name_plural': 'families'},
        ),
    ]
