# Generated by Django 5.1.6 on 2025-02-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_family_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='towersuser',
            name='alias',
            field=models.CharField(blank=True, null=True),
        ),
    ]
