# Generated by Django 5.1.6 on 2025-02-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_towersuser_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towersuser',
            name='alias',
            field=models.CharField(default='', unique=True),
            preserve_default=False,
        ),
    ]
