# Generated by Django 5.1.6 on 2025-02-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_towersuser_alias"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verify_expiration",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verify_key",
        ),
    ]
