# Generated by Django 5.1.6 on 2025-03-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_height_towersuser_height_shoulders'),
    ]

    operations = [
        migrations.AddField(
            model_name='towersuser',
            name='height_arms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
