# Generated by Django 5.1.8 on 2025-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_useremail_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlegroupmodule",
            name="delete_on_expire",
            field=models.BooleanField(default=True),
        ),
    ]
