# Generated by Django 5.1.8 on 2025-07-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_googlegroupmodule_delete_on_expire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googlegroupmodule",
            name="delete_on_expire",
        ),
        migrations.AddField(
            model_name="googlegroup",
            name="delete_on_expire",
            field=models.BooleanField(default=True),
        ),
    ]
