# Generated by Django 5.1.11 on 2025-08-03 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_orderdeliveryaddress_zone_and_more'),
        ('user', '0020_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='order.order'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(10, 'OWNED'), (20, 'FROM_ORDER')]),
        ),
    ]
