# Generated by Django 5.1.11 on 2025-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_userproduct_order_alter_userproduct_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlegroupmodule",
            name="exclude_membership",
            field=models.BooleanField(default=False),
        ),
    ]
