# Generated by Django 5.1.11 on 2025-08-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_googlegroupuser"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="googlegroupuser",
            unique_together={("group", "email")},
        ),
    ]
