# Generated by Django 5.1.11 on 2025-08-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_alter_googlegroupuser_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="googlegroupmodule",
            old_name="exclude_membership",
            new_name="exclude_active",
        ),
    ]
