# Generated by Django 5.1.14 on 2026-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0026_useremail_email_verified"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-created_at"], name="user_user_created_02326c_idx"
            ),
        ),
    ]
