# Generated by Django 5.1.15 on 2026-05-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0034_create_orders_for_registrations"),
        ("product", "0013_productimage_order"),
        ("user", "0027_user_user_user_created_02326c_idx"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userproduct",
            unique_together={("user", "product", "order")},
        ),
    ]
