# Generated by Django 5.1.15 on 2026-05-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_alter_userproduct_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlegroupuser",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
