# Generated by Django 5.2.16 on 2026-07-20 15:23

from django.db import migrations, models

import user.enums


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_alter_googlegroupuser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlegroupuser",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "OWNER"), (20, "MANAGER"), (30, "MEMBER")],
                default=user.enums.GoogleGroupUserRole["MEMBER"],
            ),
        ),
    ]
