# Generated by Django 5.2.16 on 2026-07-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0008_alter_member_picture"),
        ("user", "0030_googlegroupuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlegroupmodule",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_group_models",
                to="legal.role",
            ),
        ),
    ]
