# Generated by Django 5.2.17 on 2026-09-06 07:59

from django.db import migrations, models

from user.utils import generate_membership_number


def generate_user_membership_number(apps, schema_editor):
    User = apps.get_model("user", "User")

    for user_obj in User.objects.all():
        user_obj.membership_number = generate_membership_number()
        user_obj.save(update_fields=("membership_number",))


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0031_googlegroupmodule_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.RunPython(generate_user_membership_number, reverse_code=migrations.RunPython.noop),
    ]
