# Generated by Django 5.2.17 on 2026-09-06 08:01

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_user_membership_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="membership_number",
            field=models.CharField(
                default=user.utils.generate_membership_number,
                max_length=12,
                unique=True,
            ),
        ),
    ]
