# Generated by Django 5.2.17 on 2026-09-11 11:36

import comunicat.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0033_alter_user_membership_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                default=comunicat.utils.crypto.gen_random_token, max_length=255
            ),
        ),
    ]
