# Generated by Django 5.2.17 on 2026-10-03 08:09

import comunicat.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0034_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                default=comunicat.utils.crypto.gen_random_token,
                max_length=255,
                unique=True,
            ),
        ),
    ]
