# Generated by Django 5.1.14 on 2025-11-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programcourseprice",
            name="birthday_from",
        ),
        migrations.RemoveField(
            model_name="programcourseprice",
            name="birthday_to",
        ),
        migrations.AddField(
            model_name="programcourseprice",
            name="age_from",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programcourseprice",
            name="age_to",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
