# Generated by Django 5.1.14 on 2025-11-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_remove_programcourseprice_birthday_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcourse",
            name="signup_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
