# Generated by Django 5.1.14 on 2025-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0004_programcourseregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcourseprice",
            name="from_registrations",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
