# Generated by Django 5.1.14 on 2025-12-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0005_programcourseprice_from_registrations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programcourseprice",
            old_name="from_registrations",
            new_name="min_registrations",
        ),
    ]
