# Generated by Django 5.1.14 on 2025-12-04 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activity",
            "0006_rename_from_registrations_programcourseprice_min_registrations",
        ),
        ("payment", "0042_entity_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcourseregistration",
            name="line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_registration",
                to="payment.paymentline",
            ),
        ),
    ]
