# Generated by Django 5.1.14 on 2025-12-04 18:22

import activity.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0007_programcourseregistration_line"),
        ("payment", "0042_entity_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcourseregistration",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "REQUESTED"),
                    (1, "PROCESSING"),
                    (2, "ACTIVE"),
                    (3, "EXPIRED"),
                ],
                default=activity.enums.ProgramCourseRegistrationStatus["REQUESTED"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programcourseregistration",
            unique_together={("course", "entity")},
        ),
    ]
