# Generated by Django 5.1.8 on 2025-07-05 12:31

import order.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderproduct_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'PROCESSING'), (2, 'COMPLETED'), (3, 'CANCELLED')], default=order.enums.OrderStatus['CREATED']),
        ),
    ]
