# Generated by Django 5.1.8 on 2025-07-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_orderlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="origin_module",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "ORG"), (20, "TOWERS")], default=20
            ),
            preserve_default=False,
        ),
    ]
