# Generated by Django 5.1.8 on 2025-07-18 14:07

import comunicat.utils.models
import order.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_order_origin_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "name",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(10, "PICK_UP"), (20, "IN_PERSON"), (30, "DELIVERY")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="orderdelivery",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "PICK_UP"), (20, "IN_PERSON"), (30, "DELIVERY")],
                default=order.enums.OrderDeliveryType["PICK_UP"],
            ),
        ),
    ]
