# Generated by Django 5.1.8 on 2025-07-18 14:12

import comunicat.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_deliveryprovider_alter_orderdelivery_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryprovider",
            name="description",
            field=models.JSONField(
                default=comunicat.utils.models.language_field_default
            ),
        ),
    ]
