# Generated by Django 5.1.8 on 2025-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_deliveryprovider_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryprovider",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
