# Generated by Django 5.1.8 on 2025-07-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_deliveryprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprice',
            name='max_grams',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
