# Generated by Django 5.1.8 on 2025-07-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_deliveryprice_max_grams"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryprice",
            options={"ordering": ("price", "max_grams")},
        ),
        migrations.RenameField(
            model_name="deliveryprice",
            old_name="amount",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="deliveryprice",
            old_name="amount_currency",
            new_name="price_currency",
        ),
    ]
