# Generated by Django 5.1.8 on 2025-07-19 17:15

import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_country_options_region"),
        ("order", "0015_deliveryprovider_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryprice",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="amount_unit_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="OrderDeliveryAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("address", models.CharField(max_length=255)),
                ("apartment", models.CharField(blank=True, max_length=10, null=True)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("postcode", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=255)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_addresses",
                        to="data.country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_addresses",
                        to="data.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.AddField(
            model_name="orderdelivery",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery",
                to="order.orderdeliveryaddress",
            ),
        ),
    ]
