# Generated by Django 5.1.8 on 2025-07-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderdelivery_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdelivery',
            name='type',
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='order.deliveryprovider'),
        ),
    ]
