# Generated by Django 5.1.8 on 2025-07-19 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_orderproduct_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('date', models.DateField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='order.deliveryprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
