# Generated by Django 5.1.8 on 2025-07-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_zone_country_zone"),
        ("order", "0021_deliverydate"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryprice",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_prices",
                to="data.zone",
            ),
        ),
    ]
