# Generated by Django 5.1.11 on 2025-07-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0022_deliveryprice_zone"),
        ("payment", "0034_paymentorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order",
                to="payment.paymentorder",
            ),
        ),
    ]
