# Generated by Django 5.1.11 on 2025-07-25 09:30

import comunicat.rest.utils.helpers
import order.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0023_order_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.CharField(
                default=comunicat.rest.utils.helpers.generate_reference, max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "CREATED"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELLED"),
                    (50, "ABANDONED"),
                ],
                default=order.enums.OrderStatus["CREATED"],
            ),
        ),
        migrations.AlterField(
            model_name="orderlog",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "CREATED"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELLED"),
                    (50, "ABANDONED"),
                ]
            ),
        ),
    ]
