# Generated by Django 5.1.11 on 2025-07-25 09:31

import comunicat.rest.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0024_order_reference_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference",
            field=models.CharField(
                default=comunicat.rest.utils.helpers.generate_reference,
                max_length=8,
                unique=True,
            ),
        ),
    ]
