# Generated by Django 5.1.11 on 2025-07-26 21:54

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0025_alter_order_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdelivery",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default_currency="SEK",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderdelivery",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderdelivery",
            name="vat",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
