# Generated by Django 5.1.11 on 2025-07-26 21:54

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0026_orderdelivery_amount_orderdelivery_amount_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdelivery",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="SEK", max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="orderdelivery",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                default="SEK",
                editable=False,
                max_length=3,
            ),
        ),
    ]
