# Generated by Django 5.1.11 on 2025-07-26 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_zone_country_zone"),
        ("order", "0027_alter_orderdelivery_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdeliveryaddress",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_addresses",
                to="data.region",
            ),
        ),
    ]
