# Generated by Django 5.1.11 on 2025-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0028_orderdeliveryaddress_zone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="quantity_given",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
