# Generated by Django 5.1.14 on 2026-01-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0029_orderproduct_quantity_given"),
        ("payment", "0042_entity_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdelivery",
            name="line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery",
                to="payment.paymentline",
            ),
        ),
    ]
