# Generated by Django 5.1.14 on 2026-01-27 12:59

import django.db.models.deletion
from django.db import migrations, models


def update_deliveries_with_prices(apps, schema_editor):
    OrderDelivery = apps.get_model("order", "OrderDelivery")
    DeliveryPrice = apps.get_model("order", "DeliveryPrice")

    delivery_price_by_key = {
        (
            delivery_price_obj.provider_id,
            delivery_price_obj.country_id,
            delivery_price_obj.price,
            delivery_price_obj.vat,
        ): delivery_price_obj
        for delivery_price_obj in DeliveryPrice.objects.all()
    }

    order_delivery_updates = []

    for order_delivery_obj in OrderDelivery.objects.all():
        if order_delivery_obj.address:
            delivery_price_obj = delivery_price_by_key[
                (
                    order_delivery_obj.provider_id,
                    order_delivery_obj.address.country_id,
                    order_delivery_obj.amount,
                    order_delivery_obj.vat,
                )
            ]
            order_delivery_obj.price = delivery_price_obj
            order_delivery_updates.append(order_delivery_obj)

    if order_delivery_updates:
        OrderDelivery.objects.bulk_update(order_delivery_updates, fields=("price",))


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0030_orderdelivery_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdelivery",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="order.deliveryprice",
            ),
        ),
        migrations.RunPython(update_deliveries_with_prices, migrations.RunPython.noop),
    ]
