# Generated by Django 5.1.15 on 2026-04-16 15:19

import django.db.models.deletion
from django.db import migrations, models

import order.enums


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0032_orderregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order",
                to="order.orderdelivery",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "CREATED"),
                    (15, "REQUESTED"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELLED"),
                    (50, "ABANDONED"),
                ],
                default=order.enums.OrderStatus["CREATED"],
            ),
        ),
        migrations.AlterField(
            model_name="orderlog",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "CREATED"),
                    (15, "REQUESTED"),
                    (20, "PROCESSING"),
                    (30, "COMPLETED"),
                    (40, "CANCELLED"),
                    (50, "ABANDONED"),
                ]
            ),
        ),
    ]
