# Generated by Django 5.1.15 on 2026-04-16 15:19
import itertools

import django.db.models.deletion
import order.enums
from django.db import migrations, models

from event.enums import RegistrationStatus
from order.enums import OrderStatus


def create_orders_for_registrations(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    OrderRegistration = apps.get_model("order", "OrderRegistration")
    Registration = apps.get_model("event", "Registration")

    registration_objs = list(
        Registration.objects.filter(
            status=RegistrationStatus.ACTIVE,
            event__modules__require_approve=True,
            line__isnull=False,
        )
        .select_related(
            "event", "line", "price", "line__payment", "line__payment__entity"
        )
        .order_by("event_id", "line__payment_id")
    )

    order_creates = []
    order_registration_creates = []

    for __, current_registration_objs in itertools.groupby(
        registration_objs,
        lambda r_obj: (r_obj.event_id, r_obj.line.payment_id),
    ):
        current_registration_objs = list(current_registration_objs)
        order_obj = Order(
            entity=current_registration_objs[0].line.payment.entity,
            status=OrderStatus.COMPLETED,
            origin_module=current_registration_objs[0].event.module,
            origin_language=current_registration_objs[0].entity.preferred_language,
        )
        order_creates.append(order_obj)
        for current_registration_obj in current_registration_objs:
            order_registration_creates.append(
                OrderRegistration(
                    order=order_obj,
                    registration=current_registration_obj,
                    line=current_registration_obj.line,
                    amount=current_registration_obj.price.amount,
                )
            )

    if order_creates:
        Order.objects.bulk_create(order_creates)

    if order_registration_creates:
        OrderRegistration.objects.bulk_create(order_registration_creates)


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0033_alter_order_delivery_alter_order_status_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_orders_for_registrations, migrations.RunPython.noop
        ),
    ]
