# Generated by Django 5.2.16 on 2026-07-26 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0034_create_orders_for_registrations"),
        ("payment", "0051_alter_accountevent_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAccounts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "payment_credit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_accounts_payment_credit",
                        to="payment.account",
                    ),
                ),
                (
                    "payment_debit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_accounts_payment_debit",
                        to="payment.account",
                    ),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="order.deliveryprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "delivery accounts",
                "verbose_name_plural": "delivery accounts",
            },
        ),
    ]
