# Generated by Django 5.2.17 on 2026-08-20 08:32

import order.enums
from django.db import migrations, models

from order.enums import OrderType


def update_orders_type(apps, schema_editor):
    Order = apps.get_model("order", "Order")

    Order.objects.filter(registrations__isnull=False).update(type=OrderType.REGISTRATION)


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0035_deliveryaccounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "PRODUCT"), (20, "REGISTRATION"), (30, "MEMBERSHIP")],
                default=order.enums.OrderType["PRODUCT"],
            ),
        ),
        migrations.RunPython(
            update_orders_type, migrations.RunPython.noop
        ),
    ]
