# Generated by Django 5.2.17 on 2026-08-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0041_eventaccounts"),
        ("membership", "0012_alter_membershipmodule_amount_currency"),
        ("order", "0037_ordermembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermembership",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_memberships",
                to="membership.membershipmodule",
            ),
        ),
        migrations.AlterField(
            model_name="orderregistration",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_registrations",
                to="event.registration",
            ),
        ),
    ]
