# Generated by Django 5.2.17 on 2026-09-30 10:48

import django.db.models.deletion
import djmoney.models.fields
import order.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0039_alter_order_type_ordercourse"),
        ("payment", "0064_paymentrequest_paymentrequestline_paymentrequestlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "PRODUCT"),
                    (20, "REGISTRATION"),
                    (30, "MEMBERSHIP"),
                    (40, "COURSE"),
                    (50, "REQUEST"),
                ],
                default=order.enums.OrderType["PRODUCT"],
            ),
        ),
        migrations.CreateModel(
            name="OrderRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("SEK", "Swedish Krona")],
                        default="SEK",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2, default_currency="SEK", max_digits=7
                    ),
                ),
                ("vat", models.PositiveSmallIntegerField(default=0)),
                (
                    "line",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_requests",
                        to="payment.paymentline",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="order.order",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_requests",
                        to="payment.paymentrequestline",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
