# Generated by Django 5.1.8 on 2025-07-18 15:13

import comunicat.utils.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "name",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("is_starred", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
