# Generated by Django 5.1.8 on 2025-07-22 09:09

import uuid

import django.db.models.deletion
from django.db import migrations, models

import comunicat.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_country_options_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "name",
                    models.JSONField(
                        default=comunicat.utils.models.language_field_default
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="country",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="data.zone",
            ),
        ),
    ]
