# Generated by Django 5.1.11 on 2025-07-30 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_country_code_mapping_alter_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country_code_mapping',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
