name: Build and push
description: Builds and pushes an image to the registry

inputs:
  name:
    description: The image name
    required: true
  github_token:
    description: The GitHub token secret
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}

    - name: Build image
      shell: bash
      run: docker build ${{ inputs.name }} --tag ghcr.io/castellersestocolm/${{ inputs.name }}:${{ github.sha }} --tag ghcr.io/castellersestocolm/${{ inputs.name }}:${{ github.ref_name }}

    - name: Log in to registry
      shell: bash
      run: echo "${{ inputs.github_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      shell: bash
      run: docker push ghcr.io/castellersestocolm/${{ inputs.name }} --all-tags
