name: Deploy

on:
  push:
    branches:
      - master
      - dev

env:
  REGISTRY: ghcr.io
  BUILD_TARGET: live

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-backend:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    name: Build backend
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - uses: ./.github/actions/build-and-push
      name: Build backend
      with:
        name: backend
        github_token: ${{ secrets.GITHUB_TOKEN }}
        build_target: ${{ env.BUILD_TARGET }}
        cert_swish_cert: "${{ secrets.CERT_SWISH_CERT }}"
        cert_swish_key: "${{ secrets.CERT_SWISH_KEY }}"
        cert_swish_verify: "${{ secrets.CERT_SWISH_VERIFY }}"
        cert_apple_org_cert: "${{ secrets.CERT_APPLE_ORG_CERT }}"
        cert_apple_org_key: "${{ secrets.CERT_APPLE_ORG_KEY }}"
        cert_apple_org_verify: "${{ secrets.CERT_APPLE_ORG_VERIFY }}"
        cert_apple_towers_cert: "${{ secrets.CERT_APPLE_TOWERS_CERT }}"
        cert_apple_towers_key: "${{ secrets.CERT_APPLE_TOWERS_KEY }}"
        cert_apple_towers_verify: "${{ secrets.CERT_APPLE_TOWERS_VERIFY }}"
        cred_google_app: "${{ secrets.CRED_GOOGLE_APP }}"

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ github.ref_name }}
    needs: [ build-backend ]
    name: Deploy

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - uses: appleboy/ssh-action@v1.2.2
      name: Deploy
      env:
        BUILD_TAG: ${{ github.sha }}
        BUILD_TARGET: ${{ env.BUILD_TARGET }}
      with:
        host: ${{ secrets.SSH_REMOTE_HOST }}
        username: ${{ secrets.SSH_REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: BUILD_TAG,BUILD_TARGET
        script: |
          docker stack deploy --with-registry-auth --compose-file website/docker-compose-prod.yml --detach=true comunicat
          docker image prune --all --force
