name: Deploy

on:
  push:
    branches: [ "master", "dev" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Build backend
    
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build-and-push
      name: Build backend
      with:
        name: backend
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build-frontend-org:
    runs-on: ubuntu-latest
    name: Build frontend-org
    
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build-and-push
      name: Build frontend-org
      with:
        name: frontend-org
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build-frontend-towers:
    runs-on: ubuntu-latest
    name: Build frontend-towers
    
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build-and-push
      name: Build frontend-towers
      with:
        name: frontend-towers
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
  build-pinyator:
    runs-on: ubuntu-latest
    name: Build pinyator
    
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build-and-push
      name: Build pinyator
      with:
        name: pinyator
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
  build-php:
    runs-on: ubuntu-latest
    name: Build php
    
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build-and-push
      name: Build php
      with:
        name: php
        github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - uses: serversideup/github-action-docker-swarm-deploy@v3
        with:
          ssh_deploy_private_key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh_remote_hostname: "${{ secrets.SSH_REMOTE_HOST }}"
          registry: "ghcr.io"
          registry-username: "${{ github.actor }}"
          registry-token: "${{ secrets.GITHUB_TOKEN }}"
          stack_name: "comunicat"
