name: Deploy

on:
  push:
    branches: [ "master", "dev" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Build backend
    
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build-and-push
      name: Build backend
      with:
        name: backend
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build-frontend-org:
    runs-on: ubuntu-latest
    name: Build frontend-org
    
    steps:
    - uses: actions/checkout@v4
    - name: Build frontend-org
      run: docker build frontend-org --tag comunicat/frontend-org:${{ github.sha }} --tag comunicat/frontend-org:${{ github.ref_name }}

  build-frontend-towers:
    runs-on: ubuntu-latest
    name: Build frontend-towers
    
    steps:
    - uses: actions/checkout@v4
    - name: Build frontend-towers
      run: docker build frontend-towers --tag comunicat/frontend-towers:${{ github.sha }} --tag comunicat/frontend-towers:${{ github.ref_name }}
      
  build-pinyator:
    runs-on: ubuntu-latest
    name: Build pinyator
    
    steps:
    - uses: actions/checkout@v4
    - name: Build pinyator
      run: docker build pinyator --tag comunicat/pinyator:${{ github.sha }} --tag comunicat/pinyator:${{ github.ref_name }}
      
  build-php:
    runs-on: ubuntu-latest
    name: Build php
    
    steps:
    - uses: actions/checkout@v4
    - name: Build php
      run: docker build php --tag comunicat/php:${{ github.sha }} --tag comunicat/php:${{ github.ref_name }}
