export const API_EVENTS_LIST_PAGE_SIZE = 5;
export const API_REGISTRATIONS_LIST_PAGE_SIZE = 5;
export const API_PAYMENTS_LIST_PAGE_SIZE = 5;
export const API_EXPENSES_LIST_PAGE_SIZE = 5;
export const API_ORDERS_LIST_PAGE_SIZE = 5;
export const API_PROGRAM_COURSE_REGISTRATIONS_LIST_PAGE_SIZE = 10;
export const API_LEGAL_GROUP_LIST_PAGE_SIZE = 1;
export const API_DOCUMENTS_LIST_PAGE_SIZE = 16;

export const WP_API_POSTS_LIST_PAGE_SIZE = 10;

export const PAYMENT_SWISH_NUMBER = "123 068 88 20";
